- .github/workflows/renovate.yml
- renovate.json
Need to set up SLACK_OSS_GITHUB_TOKEN first
> Integrate Renovate for dependencies

- build.gradle.kts
- gradle/libs.versions.toml
- slack-plugin/build.gradle.kts
These are only used in our internal shim for tracing and not in SGP public
> Remove Wire refs

- slack-plugin/src/main/kotlin/slack/gradle/SlackGradleUtil.kt
- slack-plugin/src/main/kotlin/slack/stats/ModuleStats.kt
- Fix default in multivariant libs (which should be "debug")
- Fix the LocTask not depending on the compilation sources lifecycle task. This would result in occasional build flakes where the final generated dir was not present if it hadn't built (coincidentally) before the task ran
> Fix a couple bugs in modscore

- build.gradle.kts
- gradle/libs.versions.toml
- slack-plugin/src/main/kotlin/slack/dependencyrake/DependencyRake.kt
- slack-plugin/src/main/kotlin/slack/gradle/SlackRootPlugin.kt
This includes fixes for assets and theme attrs along with a new API for declaring primary identifiers (allowing us to remove our own shim for this for the most part)
> Update to DAGP 1.2.0

- slack-plugin/src/main/kotlin/slack/gradle/SlackBasePlugin.kt
- slack-plugin/src/main/kotlin/slack/gradle/StandardProjectConfigurations.kt
See https://github.com/diffplug/spotless/issues/1213. Better performance too since we use the same config for every project
> Predeclare spotless deps instead

- slack-plugin/src/main/kotlin/slack/gradle/SlackTools.kt
> Don't write thermals logs if currently cleaning

- slack-plugin/src/main/kotlin/slack/gradle/SlackBasePlugin.kt
> Fix hamcrest dep logic

- README.md
- slack-plugin/src/main/kotlin/slack/gradle/SlackProperties.kt
- slack-plugin/src/main/kotlin/slack/gradle/StandardProjectConfigurations.kt
More work on the reusability front
> Add detekt configs + document auto-applied plugins

- slack-plugin/src/main/kotlin/slack/gradle/SlackExtension.kt
- slack-plugin/src/main/kotlin/slack/gradle/SlackProperties.kt
This allows us to avoid kapt in more places
https://github.com/sergei-lapin/napt
> Add support for napt in place of kapt

- build.gradle.kts
- slack-plugin/src/main/kotlin/slack/gradle/SlackBasePlugin.kt
- slack-plugin/src/main/kotlin/slack/gradle/SlackRootPlugin.kt
These are issues that are now resolves
> Clean up some now-outdated guards

- slack-plugin/src/main/kotlin/slack/gradle/SlackGradleUtil.kt
Was pointing at the wrong name var and now includes project info too
> Fix namedLazy error message

- .github/workflows/renovate.yml
Reverts slackhq/slack-gradle-plugin#105
> Revert "Update renovatebot/github-action action to v32.190.4"

- renovate.json
> Update renovate action monthly

- slack-plugin/src/main/kotlin/slack/gradle/SlackExtension.kt
- slack-plugin/src/main/kotlin/slack/gradle/dependencies/SlackDependencies.kt
- slack-plugin/src/main/kotlin/slack/stats/ModuleStats.kt
> Remove dagger-android support

- gradle/libs.versions.toml
- settings.gradle.kts
- slack-plugin/build.gradle.kts
- slack-plugin/src/main/kotlin/slack/gradle/SlackBasePlugin.kt
- slack-plugin/src/main/kotlin/slack/gradle/tasks/BootstrapTask.kt
- slack-plugin/src/main/kotlin/slack/stats/ModuleStats.kt
Integrates https://github.com/autonomousapps/gradle-best-practices-plugin
Knew about these two issues before, but was a good forcing function to properly address them
> Add best practices plugin + two fixes

- slack-plugin/src/main/kotlin/slack/gradle/SlackBasePlugin.kt
- slack-plugin/src/main/kotlin/slack/gradle/SlackRootPlugin.kt
- slack-plugin/src/main/kotlin/slack/gradle/tasks/BootstrapTask.kt
> Only configure bootstrap conditionally

- slack-plugin/src/main/kotlin/slack/gradle/SlackProperties.kt
- slack-plugin/src/main/kotlin/slack/gradle/StandardProjectConfigurations.kt
Resolves #44, also mentions they should be debuggable
> Check that androidTest sources have manifests

- build.gradle.kts
> Add some new compiler args

- slack-plugin/src/main/kotlin/slack/unittest/UnitTestPlugin.kt
This allows us to easily test and build ci unit tests, useful for both profiling builds and also possible warming the cache in another step.
> Add compileCiUnitTest lifecycle task

- slack-plugin/src/main/kotlin/slack/gradle/SlackBasePlugin.kt
These can no longer be added at this point and isn't necessary anymore either
> Remove eithernet opt-ins

- slack-plugin/src/main/kotlin/slack/gradle/GlobalConfig.kt
- slack-plugin/src/main/kotlin/slack/gradle/Platforms.kt
- slack-plugin/src/main/kotlin/slack/gradle/SlackBasePlugin.kt
- slack-plugin/src/main/kotlin/slack/gradle/SlackGradleUtil.kt
- slack-plugin/src/main/kotlin/slack/gradle/SlackProperties.kt
- slack-plugin/src/main/kotlin/slack/gradle/StandardProjectConfigurations.kt
- slack-plugin/src/main/kotlin/slack/gradle/configureBuildTags.kt
- slack-plugin/src/main/kotlin/slack/gradle/util/PropertyUtil.kt
> Rework how bugsnag is enabled

- slack-plugin/src/main/kotlin/slack/gradle/util/ThermalsWatcher.kt
> Catch and print errors with thermal closes

- sgp-monkeypatch-agp/src/main/kotlin/com/android/build/gradle/internal/tasks/MergeFilesTask.kt
Trying to debug some things as the previous version isn't working
> Add more logging to monkeypatch and also sort by absolute path

- gradle/libs.versions.toml
- slack-plugin/build.gradle.kts
> Add jna-platform to ensure matching versions

- agp-handlers/agp-handler-74/build.gradle.kts
- agp-handlers/agp-handler-74/src/main/kotlin/slack/gradle/agphandler/v74/AgpHandlerFactory74.kt
- agp-handlers/agp-handler-80/build.gradle.kts
- agp-handlers/agp-handler-api/build.gradle.kts
- slack-plugin/build.gradle.kts
- slack-plugin/src/main/kotlin/Aliases.kt
- slack-plugin/src/main/kotlin/slack/gradle/ApkVersioningPlugin.kt
- slack-plugin/src/main/kotlin/slack/gradle/GlobalConfig.kt
- slack-plugin/src/main/kotlin/slack/gradle/GradleExt.kt
- slack-plugin/src/main/kotlin/slack/gradle/Platforms.kt
- slack-plugin/src/main/kotlin/slack/gradle/SlackBasePlugin.kt
- slack-plugin/src/main/kotlin/slack/gradle/SlackExtension.kt
- slack-plugin/src/main/kotlin/slack/gradle/SlackGradleUtil.kt
- slack-plugin/src/main/kotlin/slack/gradle/SlackRootPlugin.kt
- slack-plugin/src/main/kotlin/slack/gradle/SlackTools.kt
- slack-plugin/src/main/kotlin/slack/gradle/StandardProjectConfigurations.kt
- slack-plugin/src/main/kotlin/slack/gradle/configureBuildTags.kt
- slack-plugin/src/main/kotlin/slack/gradle/permissionchecks/PermissionChecks.kt
- slack-plugin/src/main/kotlin/slack/gradle/tasks/AndroidTestApksTask.kt
- slack-plugin/src/main/kotlin/slack/gradle/tasks/BootstrapTask.kt
- slack-plugin/src/main/kotlin/slack/gradle/tasks/CheckDependencyVersionsTask.kt
- slack-plugin/src/main/kotlin/slack/gradle/tasks/InstallCommitHooksTask.kt
- slack-plugin/src/main/kotlin/slack/gradle/tasks/PrintFossaDependencies.kt
- slack-plugin/src/main/kotlin/slack/gradle/tasks/robolectric/UpdateRobolectricJarsTask.kt
- slack-plugin/src/main/kotlin/slack/gradle/util/kgpUtil.kt
- slack-plugin/src/main/kotlin/slack/stats/ModuleStats.kt
> Remove kotlin DSL dependency

- slack-plugin/src/main/kotlin/slack/gradle/SlackTools.kt
- slack-plugin/src/main/kotlin/slack/gradle/util/ThermalsWatcher.kt
> Gracefully catch JNA issues

- slack-plugin/src/main/kotlin/slack/gradle/util/ThermalsWatcher.kt
These don't seem to be recoverable/intermittent when they happen, so let's just stop recording in the even that they happen for now to reduce noise.
> Stop recording thermals if we receive an error or unknown state

- slack-plugin/src/main/kotlin/slack/gradle/SlackProperties.kt
- slack-plugin/src/main/kotlin/slack/gradle/StandardProjectConfigurations.kt
Reverts slackhq/slack-gradle-plugin#276. I completely forgot that lint.xml is a thing and that's the right solution for this case.
> Revert "Add lintErrorRuleIds property"

- slack-plugin/src/main/kotlin/slack/gradle/GlobalConfig.kt
- slack-plugin/src/main/kotlin/slack/gradle/SlackBasePlugin.kt
- slack-plugin/src/main/kotlin/slack/gradle/SlackProperties.kt
- slack-plugin/src/main/kotlin/slack/gradle/StandardProjectConfigurations.kt
- slack-plugin/src/main/kotlin/slack/gradle/lint/LintTasks.kt
- slack-plugin/src/main/kotlin/slack/unittest/UnitTests.kt
> Add affected projects property as inputs to configuring tests, android tests, and lint.

- slack-plugin/src/main/kotlin/slack/gradle/StandardProjectConfigurations.kt
- slack-plugin/src/main/kotlin/slack/gradle/lint/LintTasks.kt
- slack-plugin/src/main/kotlin/slack/unittest/UnitTests.kt
> [Skippy] Log verbosely in debug mode when skipping task deps

- slack-plugin/src/main/kotlin/slack/gradle/avoidance/GlobUtil.kt
This way we can output a useful `toString()` for logs
> [Skippy] Implement StringPathMatcher for logging

- slack-plugin/src/test/kotlin/slack/gradle/avoidance/AffectedProjectsComputerTest.kt
Wasn't working before because I forgot to pass in the test `fileSystem` instance. Now it runs fully in-memory.
> [Skippy] Use FakeFileSystem in tests

- slack-plugin/src/main/kotlin/slack/gradle/SlackGradleUtil.kt
- slack-plugin/src/main/kotlin/slack/gradle/lint/LintTasks.kt
- slack-plugin/src/main/kotlin/slack/gradle/tasks/CheckDependencyVersionsTask.kt
- slack-plugin/src/main/kotlin/slack/gradle/tasks/PrintFossaDependencies.kt
- slack-plugin/src/main/kotlin/slack/stats/ModuleStats.kt
> Rename capitalizeUS + remove deprecated use

- slack-plugin/src/main/kotlin/slack/gradle/SlackRootPlugin.kt
- slack-plugin/src/main/kotlin/slack/gradle/StandardProjectConfigurations.kt
- slack-plugin/src/main/kotlin/slack/gradle/lint/DetektTasks.kt
> Add new `globalDetekt` + consolidate detekt logic + add skippy support

- slack-plugin/src/main/kotlin/slack/unittest/UnitTests.kt
> Don't enable kover on the platform project

- slack-plugin/src/main/kotlin/slack/gradle/SlackTools.kt
Better to error about them than fail the build
> Gracefully handle extensions that fail to load

- slack-plugin/src/main/kotlin/slack/gradle/StandardProjectConfigurations.kt
Now we have to set the target language version instead.
> Update from `useK2` to new approach for K2 testing

- slack-plugin/src/main/kotlin/slack/gradle/SlackTools.kt
> Add debugging for slacktools extension loading + fix classloader

- slack-plugin/src/main/kotlin/slack/gradle/SlackExtension.kt
- slack-plugin/src/main/kotlin/slack/gradle/SlackProperties.kt
> Support dagger KSP

- slack-plugin/src/main/kotlin/slack/unittest/UnitTests.kt
https://github.com/Kotlin/kotlinx-kover/issues/362
> Work around kover bug

- slack-plugin/src/main/kotlin/slack/gradle/StandardProjectConfigurations.kt
- slack-plugin/src/main/kotlin/slack/gradle/avoidance/AffectedProjectsComputer.kt
- slack-plugin/src/main/kotlin/slack/gradle/avoidance/AffectedProjectsResult.kt
- slack-plugin/src/main/kotlin/slack/gradle/avoidance/ComputeAffectedProjectsTask.kt
- slack-plugin/src/test/kotlin/slack/gradle/avoidance/AffectedProjectsComputerTest.kt
> Log computed androidTest projects in Skippy

- slack-plugin/src/main/kotlin/slack/gradle/SlackGradleUtil.kt
- slack-plugin/src/test/kotlin/slack/gradle/SlackGradleUtilTest.kt
Made a more generalized regex solution and also added a test for apple's output
> Improve git version matching

- slack-plugin/src/main/kotlin/slack/gradle/tasks/BootstrapTask.kt
> Update bootstrap opens comment for clarity

- gradle.properties
These aren't necessary anymore
> Clean up jvm args in project

- slack-plugin/src/main/kotlin/slack/gradle/SlackRootPlugin.kt
- slack-plugin/src/main/kotlin/slack/gradle/tasks/BootstrapTask.kt
> Fix bootstrap not using jvm vendor property

- slack-plugin/src/main/kotlin/slack/gradle/GlobalConfig.kt
- slack-plugin/src/main/kotlin/slack/gradle/SlackExtension.kt
- slack-plugin/src/main/kotlin/slack/gradle/SlackVersions.kt
- slack-plugin/src/main/kotlin/slack/gradle/StandardProjectConfigurations.kt
Not all projects consuming SGP need it
> Make robolectric optional

- .github/workflows/code-review.yml
Prototype github workflow feature to enable AI assisted code review
For another Slack repo (https://github.com/fxchen/kaldb/pull/1/files), here's what the results look like
> Enable AI assisted code review

- docs/bootstrap.md
- docs/dependency-rake.md
- docs/dsl.md
- docs/utilities.md
- mkdocs.yml
This covers dependency rake, utilities, the DSL, and bootstrap
> Second pass at docs

- slack-plugin/src/main/kotlin/slack/dependencyrake/DependencyRake.kt
- slack-plugin/src/main/kotlin/slack/gradle/StandardProjectConfigurations.kt
> Add dry-run mode to dependency rake and don't run on android test projects

- slack-plugin/src/main/kotlin/slack/gradle/avoidance/AffectedProjectsComputer.kt
- slack-plugin/src/test/kotlin/slack/gradle/avoidance/PathMatcherTest.kt
> Differentiate unit vs android test and don't affect android tests if only unit tests changed

- gradle/libs.versions.toml
- skate-plugin/build.gradle.kts
- skate-plugin/src/main/kotlin/com/slack/sgp/intellij/SkateErrorHandler.kt
- skate-plugin/src/main/kotlin/com/slack/sgp/intellij/SqlDelightErrorHandler.kt
- skate-plugin/src/main/resources/META-INF/plugin.xml
First copying in and wiring up [SqlDelight's error handler](https://github.com/cashapp/sqldelight/blob/5512326251b1e9f91ddef49dda75d27405943e2f/sqldelight-idea-plugin/src/main/kotlin/app/cash/sqldelight/intellij/SqlDelightErrorHandler.kt#L35). 
and using placeholders for the `GIT_SHA`, `VERSION`, and `BUGSNAG_KEY`
> Copying in SqlDelight's Error Handler into Skate

- gradle/libs.versions.toml
- slack-plugin/src/main/kotlin/slack/gradle/SlackExtension.kt
- slack-plugin/src/main/kotlin/slack/gradle/lint/LintTasks.kt
Some source-breaking changes but no ABI breaking changes.
> Update to AGP 8.1.0

- skate-plugin/src/main/kotlin/com/slack/sgp/intellij/SkatePluginSettings.kt
> Change CHANGELOG.md name to WHATSNEW.md

- skate-plugin/build.gradle.kts
Lifted from https://github.com/cashapp/sqldelight/pull/1934. Resolves #557
> Exclude slf4j from bugsnag dep

- skate-plugin/src/main/kotlin/com/slack/sgp/intellij/ui/WhatsNewPanelFactory.kt
> Fix scrolling in HtmlPanel impl

- agp-handlers/agp-handler-api/src/main/kotlin/slack/gradle/agp/PermissionAllowlistConfigurer.kt
- slack-plugin/src/main/kotlin/slack/gradle/StandardProjectConfigurations.kt
- slack-plugin/src/main/kotlin/slack/gradle/permissionchecks/PermissionChecks.kt
Makes them a bit lazier and allows us to clean up an old TODO
> Update permission checks to use file provider APIs

- slack-plugin/src/main/kotlin/slack/gradle/StandardProjectConfigurations.kt
We'll do this as needed in consuming repos
> Remove assets merging caching control

- slack-plugin/src/main/kotlin/slack/gradle/lint/LintTasks.kt
Lifecycle always logs and is quite noisy
> Lower log level for ciLint

- renovate.json
This way they're already "merge when ready" and just need approval
> Auto-merge pip and non-major updates

- slack-plugin/src/main/kotlin/slack/gradle/SlackProperties.kt
- slack-plugin/src/main/kotlin/slack/gradle/lint/DetektTasks.kt
- slack-plugin/src/main/kotlin/slack/gradle/lint/LintTasks.kt
> Make lint and detect baselines optional

- slack-plugin/src/main/kotlin/slack/gradle/lint/DetektTasks.kt
> Use explicitly null baseline for detekt if none is specified

- slack-plugin/src/main/kotlin/slack/unittest/UnitTests.kt
> Fix deprecated forkEvery call

- docs/dsl.md
- slack-plugin/src/main/kotlin/slack/gradle/SlackExtension.kt
- slack-plugin/src/main/kotlin/slack/gradle/SlackVersions.kt
This makes it easy to add circuit up to a project.
```kotlin
slack {
features {
circuit()
}
}
```
> Implement Circuit DSL

- slack-plugin/src/main/kotlin/slack/gradle/SlackExtension.kt
- slack-plugin/src/main/kotlin/slack/gradle/dependencies/SlackDependencies.kt
> Remove autovalue APIs

- slack-plugin/src/main/kotlin/slack/gradle/SlackRootPlugin.kt
- slack-plugin/src/main/kotlin/slack/gradle/SlackTools.kt
> Update to new API for CC check

- build.gradle.kts
- gradle/libs.versions.toml
- slack-plugin/src/main/kotlin/slack/gradle/StandardProjectConfigurations.kt
The new API changes aren't very good IMO, but at least we can do this now
> Update buildconfig plugin to 5.0.0

- slack-plugin/src/main/kotlin/slack/gradle/SlackRootPlugin.kt
> Update deprecated DAGP APIs

- skippy/src/main/kotlin/com/slack/skippy/AffectedProjectsComputer.kt
- skippy/src/main/kotlin/com/slack/skippy/ComputeAffectedProjectsCli.kt
Just some little fixes around skippy
> Small fixes

- gradle/libs.versions.toml
- skate-plugin/build.gradle.kts
- skate-plugin/src/main/kotlin/com/slack/sgp/intellij/SkatePluginSettings.kt
- skate-plugin/src/main/kotlin/com/slack/sgp/intellij/codeowners/CodeOwnerFileFetcher.kt
- skate-plugin/src/main/kotlin/com/slack/sgp/intellij/codeowners/CodeOwnerRepository.kt
- skate-plugin/src/main/kotlin/com/slack/sgp/intellij/codeowners/model/CodeOwner.kt
- skate-plugin/src/main/kotlin/com/slack/sgp/intellij/codeowners/model/CodeOwnersFile.kt
- skate-plugin/src/main/kotlin/com/slack/sgp/intellij/ui/CodeOwnerWidget.kt
- skate-plugin/src/main/kotlin/com/slack/sgp/intellij/ui/CodeOwnerWidgetFactory.kt
- skate-plugin/src/test/kotlin/com/slack/sgp/intellij/codeowners/CodeOwnerRepositoryTest.kt
- skate-plugin/src/test/resources/test-code-ownership.csv
- skate-plugin/src/test/resources/test-code-ownership.yaml
Update code owner file parsing to new yaml format.
> Migrate from csv to yaml based owner file

- build.gradle.kts
- slack-plugin/src/main/kotlin/slack/gradle/StandardProjectConfigurations.kt
See https://jakewharton.com/kotlins-jdk-release-compatibility-flag/
> Incorporate Kotlin's -Xjdk-release option

- skate-plugin/build.gradle.kts
- skate-plugin/change-notes.html
fixed https://slack-pde.slack.com/archives/C058XKY4DRV/p1710438490115959
> update architecture for compose library

- skate-plugin/change-notes.html
> Update change note

- slack-plugin/src/main/kotlin/slack/gradle/StandardProjectConfigurations.kt
See comment in code. Relates to https://github.com/square/anvil/issues/935
> Work around AGP bug with computing non-incremental annotation processors

- agp-handlers/agp-handler-api/src/test/kotlin/slack/gradle/agp/AgpHandlersTest.kt
- config/lint/lint.xml
- gradle.properties
- gradle/libs.versions.toml
- skate-plugin/project-gen/src/jvmMain/kotlin/slack/tooling/markdown/ui/MarkdownPanel.kt
- slack-plugin/lint-baseline.xml
> Update to AGP 8.4 and lint 8.5 alphas

- skate-plugin/change-notes.html
ChangeLog has been updated in preparation for a new release!
> Update change-notes.html to prep new release

- skate-plugin/change-notes.html
> Updated version to 0.7.7 since 0.7.6 already exists

- gradle/libs.versions.toml
- settings.gradle.kts
- slack-plugin/build.gradle.kts
- slack-plugin/src/main/kotlin/slack/gradle/SlackExtension.kt
- slack-plugin/src/main/kotlin/slack/gradle/SlackProperties.kt
- slack-plugin/src/main/kotlin/slack/gradle/StandardProjectConfigurations.kt
- slack-plugin/src/main/kotlin/slack/gradle/anvil/AnvilMode.kt
- tracing/build.gradle.kts
> Streamline dagger ksp handling + remove napt

- CHANGELOG.md
- slack-plugin/src/main/kotlin/slack/gradle/SlackExtension.kt
- slack-plugin/src/main/kotlin/slack/gradle/SlackProperties.kt
> Misc compose/KGP fixes

- slack-plugin/src/main/kotlin/slack/gradle/SlackExtension.kt
- slack-plugin/src/main/kotlin/slack/gradle/SlackProperties.kt
- slack-plugin/src/main/kotlin/slack/gradle/dependencies/SlackDependencies.kt
This'll be necessary to support KSP
> Add support for anvil-ksp fork

- slack-plugin/src/main/kotlin/slack/gradle/kgp/KgpTasks.kt
With newer AGP versions, it's no longer safe to rely on the base plugin as AGP uses this now too. Instead, we explicitly only look for one of the top-level plugins we care about. This also makes it possible for us to finally start using android test fixtures in AGP 8.5.x.
> Improve KGP plugin handling

- slack-plugin/src/main/kotlin/slack/gradle/SlackProperties.kt
- slack-plugin/src/main/kotlin/slack/gradle/tasks/BootstrapTask.kt
- Add a control for setting xms values
- Remove caps on max metaspace, as this is no longer necessary in JDK 17
> Small bootstrap tweaks

- gradle/libs.versions.toml
- skate-plugin/compose-playground/src/jvmMain/kotlin/slack/tooling/compose/playground/MarkdownPlayground.kt
- skate-plugin/compose-playground/src/jvmMain/kotlin/slack/tooling/compose/playground/ProjectGenPlayground.kt
- skate-plugin/project-gen/build.gradle.kts
- skate-plugin/project-gen/src/jvmMain/kotlin/slack/tooling/markdown/ui/MarkdownPanel.kt
- skate-plugin/project-gen/src/jvmMain/kotlin/slack/tooling/projectgen/PrefixTransformation.kt
- skate-plugin/project-gen/src/jvmMain/kotlin/slack/tooling/projectgen/ProjectGenPresenter.kt
- skate-plugin/project-gen/src/jvmMain/kotlin/slack/tooling/projectgen/ProjectGenUi.kt
- skate-plugin/project-gen/src/jvmMain/kotlin/slack/tooling/projectgen/UiElement.kt
- skate-plugin/project-gen/src/jvmMain/kotlin/slack/tooling/projectgen/models.kt
Reverts PR #937 as it was causing issues with the Skate plugin. It needs to be upgraded in the future along with migrating to IntelliJ Platform Gradle Plugin 2.x.
> Revert Jewel Update 

- slack-plugin/src/main/kotlin/slack/gradle/SlackExtension.kt
> Update compose feature flags to new API

- slack-plugin/src/main/kotlin/slack/gradle/tasks/BootstrapTask.kt
Learnings from https://www.jasonpearson.dev/codecache-in-jvm-builds/ and https://www.jasonpearson.dev/softreflrupolicymspermb-in-jvm-builds/
> Intro SoftRefLRUPolicyMSPerMB + ReservedCodeCacheSize args

- CHANGELOG.md
- platforms/gradle/foundry-gradle-plugin/src/main/kotlin/foundry/gradle/FoundryProperties.kt
> Rename more properties

- platforms/intellij/skate/change-notes.html
> Add Skate release notes

- tools/cli/README.md
> Port CLI readme

- CHANGELOG.md
- build.gradle.kts
- platforms/gradle/foundry-gradle-plugin/build.gradle.kts
- platforms/gradle/foundry-gradle-plugin/src/main/kotlin/foundry/gradle/FoundryRootPlugin.kt
- platforms/gradle/foundry-gradle-plugin/src/main/kotlin/foundry/gradle/tasks/BaseDownloadTask.kt
- settings.gradle.kts
- tools/version-number/api/version-number.api
- tools/version-number/build.gradle.kts
- tools/version-number/gradle.properties
- tools/version-number/src/main/kotlin/foundry/common/versioning/VersionNumber.kt
> Extract `VersionNumber` to standalone artifact

- gradle/libs.versions.toml
- platforms/intellij/compose/src/jvmMain/kotlin/foundry/intellij/compose/markdown/ui/MarkdownPanel.kt
Fixed issue when `colorPalette.blue` returned empty list
> Fix missing link color in WhatsNew panel

- platforms/gradle/foundry-gradle-plugin/src/main/kotlin/foundry/gradle/tasks/robolectric/UpdateRobolectricJarsTask.kt
https://github.com/robolectric/robolectric/releases/tag/robolectric-4.14-beta-1
https://github.com/robolectric/robolectric/blob/master/robolectric/src/main/java/org/robolectric/plugins/DefaultSdkProvider.java#L79
> Support robolectric 4.14/SDK 35

- platforms/gradle/foundry-gradle-plugin/src/main/kotlin/foundry/gradle/dependencyrake/DependencyRake.kt
> Do not track internal state in DependencyRake

- gradle/libs.versions.toml
> Revert "Update dependency org.jetbrains.compose:compose-gradle-plugin to v1.7.1+build1910-release-1.7.1"

- platforms/gradle/foundry-gradle-plugin/src/main/kotlin/foundry/gradle/tasks/TaskExtensions.kt
This is the correct way to set this up as we don't have specific dependencies and don't necessarily require them to run if they don't need to
> Use mustRunAfter for depending on source gen tasks + add back schema task

- .github/workflows/ci.yml
From https://docs.gradle.org/current/userguide/configuration_cache.html#config_cache:secrets:configuring_encryption_key
and how androidx does it https://github.com/androidx/androidx/blob/a7f7cfb8087fbcfd117c11c188d69c9a741a17ed/.github/workflows/presubmit.yml#L41
> Enable CC sharing on CI

- platforms/gradle/foundry-gradle-plugin/src/main/kotlin/foundry/gradle/AnnotationProcessing.kt
> Add new Dagger 2.55 option

- tools/cli/api/cli.api
- tools/cli/build.gradle.kts
- tools/cli/src/main/kotlin/foundry/cli/buildkite/BuildkiteDataBindings.kt
- tools/cli/src/main/kotlin/foundry/cli/buildkite/BuildkitePipelineDsl.kt
- tools/cli/src/main/kotlin/foundry/cli/buildkite/Extensions.kt
- tools/cli/src/test/kotlin/foundry/cli/buildkite/BuildkitePipelineDslKtTest.kt
This introduces a new DSL API over our buildkite data bindings to allow for easy, more readable DSL APIs.
```kotlin
val pipeline = pipeline {
commandStep {
label = "Run tests"
command = "run-tests.sh"
env {
"ENV_VAR" to "value"
}
}
}
```
> Implement BuildkitePipelineDsl

- platforms/gradle/foundry-gradle-plugin/src/main/kotlin/foundry/gradle/topography/ModuleTopographyTask.kt
- platforms/gradle/foundry-gradle-plugin/src/test/kotlin/foundry/gradle/topography/ModuleTopographyTest.kt
> Small module topography fixes + tests

- platforms/gradle/foundry-gradle-plugin/build.gradle.kts
- platforms/gradle/foundry-gradle-plugin/src/main/kotlin/foundry/gradle/topography/DefaultFeatures.kt
- platforms/gradle/foundry-gradle-plugin/src/main/kotlin/foundry/gradle/topography/ModuleTopographyTask.kt
https://docs.gradle.org/current/userguide/reporting_problems.html. Not as rich as markdown but less noise and better integrated.
Before
After
> Use Gradle Problems API for module validation reporting

- platforms/gradle/foundry-gradle-plugin/src/main/kotlin/foundry/gradle/FoundryShared.kt
- platforms/gradle/foundry-gradle-plugin/src/main/kotlin/foundry/gradle/avoidance/ComputeAffectedProjectsTask.kt
- platforms/gradle/foundry-gradle-plugin/src/main/kotlin/foundry/gradle/stats/ModuleStats.kt
- platforms/gradle/foundry-gradle-plugin/src/main/kotlin/foundry/gradle/tasks/AndroidTestApksTask.kt
- platforms/gradle/foundry-gradle-plugin/src/main/kotlin/foundry/gradle/tasks/CheckManifestPermissionsTask.kt
- platforms/gradle/foundry-gradle-plugin/src/main/kotlin/foundry/gradle/tasks/InstallCommitHooksTask.kt
- platforms/gradle/foundry-gradle-plugin/src/main/kotlin/foundry/gradle/tasks/PrintFossaDependencies.kt
- platforms/gradle/foundry-gradle-plugin/src/main/kotlin/foundry/gradle/tasks/ValidateVersionsMatch.kt
- platforms/gradle/foundry-gradle-plugin/src/main/kotlin/foundry/gradle/tasks/robolectric/UpdateRobolectricJarsTask.kt
- platforms/gradle/foundry-gradle-plugin/src/main/kotlin/foundry/gradle/topography/ModuleTopographyTask.kt
> Use the problems API in more places

- platforms/intellij/skate/src/main/kotlin/foundry/intellij/skate/projectgen/ProjectGenWindow.kt
This shouldn't really be necessary anymore now that we run directly in Skate
> Delete project gen lock

- platforms/intellij/skate/change-notes.html
Published 0.9.0 here: https://github.com/tinyspeck/slack-gradle-plugin/actions/runs/14109600885
> Update skate release notes to v 0.9.0

- docs/platforms/gradle/architecture.md
- docs/platforms/gradle/dependency-rake.md
- docs/platforms/gradle/dsl.md
- docs/platforms/gradle/formatters-and-analysis.md
- docs/platforms/gradle/utilities.md
- platforms/gradle/foundry-gradle-plugin/src/main/kotlin/foundry/gradle/FoundryExtension.kt
> Add testing DSL + burst hook

- platforms/gradle/foundry-gradle-plugin/src/main/kotlin/foundry/gradle/FoundryProperties.kt
- platforms/gradle/foundry-gradle-plugin/src/main/kotlin/foundry/gradle/testing/UnitTests.kt
Corresponds to https://docs.gradle.org/current/dsl/org.gradle.api.tasks.testing.Test.html#org.gradle.api.tasks.testing.Test:dryRun
> Add a property for setting tests' dry run mode

- platforms/intellij/skate/change-notes.html
Just adding this change into 0.9.1: https://github.com/slackhq/foundry/pull/1301
> Add skate release notes for 0.9.1

- platforms/intellij/skate/change-notes.html
Skate `0.9.2` includes these two changes:
* https://github.com/slackhq/foundry/pull/1346
* https://github.com/slackhq/foundry/pull/1314
> Add Skate release notes for 0.9.2

- platforms/gradle/foundry-gradle-plugin/src/main/kotlin/foundry/gradle/FoundryExtension.kt
- platforms/gradle/foundry-gradle-plugin/src/main/kotlin/foundry/gradle/FoundryGradleUtil.kt
This is necessary for KSP to work in AGP 8.10.x +
> Use finalizeDsl if in android projects for DSL compat

- platforms/intellij/compose/src/jvmMain/kotlin/foundry/intellij/compose/projectgen/models.kt
> Add support for all-projects.txt file in project gen

- platforms/intellij/artifactory-authenticator/build.gradle.kts
- platforms/intellij/artifactory-authenticator/src/main/kotlin/foundry/intellij/artifactory/ArtifactoryPluginRepositoryAuthProvider.kt
- platforms/intellij/artifactory-authenticator/src/main/kotlin/foundry/intellij/artifactory/AuthPluginSettings.kt
- platforms/intellij/artifactory-authenticator/src/main/kotlin/foundry/intellij/artifactory/util.kt
Just a little bit harder to read and also safer in xml. Added backward compatibility to it as well and started storing the version
> Encode values before going to disk

- CHANGELOG.md
- platforms/gradle/foundry-gradle-plugin/src/main/kotlin/foundry/gradle/FoundryExtension.kt
> Small metro fixes
