README.md
slack-plugin/src/main/kotlin/slack/gradle/SlackExtension.kt
slack-plugin/src/main/kotlin/slack/gradle/SlackGradleUtil.kt
slack-plugin/src/main/kotlin/slack/gradle/SlackProperties.kt
slack-plugin/src/main/kotlin/slack/gradle/StandardProjectConfigurations.kt

Should allow us to remove most of our `AndroidManifest.xml` files!

Automatically configure `namespace` property for android library projects

---

README.md
slack-plugin/src/main/kotlin/slack/gradle/SlackTools.kt
slack-plugin/src/main/kotlin/slack/gradle/util/ThermalsParser.kt
slack-plugin/src/main/kotlin/slack/gradle/util/ThermalsWatcher.kt
slack-plugin/src/test/kotlin/slack/gradle/util/ThermlogParserTest.kt

This unifies our two thermals logging APIs behind a common `ThermalsWatcher` that can be simply started/stopped in `SlackTools`. This makes it fairly simple to work with and possibly easy to ~copy into other projects~ release as a separate project some day :).
Now all the core logic lives in `ThermalsWatcher.kt`. Would like to some day move the polling logic to coroutines too. 
Opportunistically cleaned up the README doc around properties too per @seankim-android's previous PR comment

Unify thermals watching API

---

gradle/libs.versions.toml
settings.gradle.kts
slack-plugin/build.gradle.kts
slack-plugin/src/main/kotlin/slack/gradle/SlackRootPlugin.kt
slack-plugin/src/main/kotlin/slack/gradle/StandardProjectConfigurations.kt

No longer necessary (or maintained) since AGP has a separate check

Remove canIDropJetifier

---

slack-plugin/src/main/kotlin/slack/gradle/StandardProjectConfigurations.kt

We were previously only setting it in application projects. Noticed this in #16 because no build types would report themselves as the default

Configure default build types in libraries too

---

slack-plugin/src/main/kotlin/slack/gradle/util/ThermalsWatcher.kt

Because we `peek()` to get the current value in the intel watcher, we need to defer setting `started()` to false until after we peek

Fix intel thermals

---

slack-plugin/src/main/kotlin/slack/gradle/AndroidSourcesConfigurer.kt
slack-plugin/src/main/kotlin/slack/gradle/SlackProperties.kt
slack-plugin/src/main/kotlin/slack/gradle/SlackRootPlugin.kt

This allows consuming repos to customize the behavior of this and use a newer version rather than rely on this repo to be the source of truth of the current latest version

Update AndroidSourcesConfigurer to allow per-repo overrides + default to compileSdk

---

slack-plugin/src/main/kotlin/slack/gradle/configureBuildTags.kt

Taken from https://github.com/gradle/gradle-enterprise-build-config-samples/blob/main/build-data-capturing-gradle-samples/capture-ge-plugin-version/gradle-ge-plugin-version.gradle

Add gradle enterprise version to build scans if present

---

slack-plugin/src/main/kotlin/slack/ProcessExtensions.kt
slack-plugin/src/main/kotlin/slack/gradle/SlackGradleUtil.kt
slack-plugin/src/main/kotlin/slack/gradle/SlackRootPlugin.kt
slack-plugin/src/main/kotlin/slack/gradle/configureBuildTags.kt

Resolves #30, using a custom `ValueSource` per https://docs.gradle.org/7.5-rc-1/release-notes.html#configuration-cache-improvements. The API is a little ugly and explicit but didn't see an easier way to do this.

Use a custom `ValueSource` to avoid unnecessary configuration cache invalidations

---

README.md
slack-plugin/src/main/kotlin/slack/gradle/SlackBasePlugin.kt
slack-plugin/src/main/kotlin/slack/gradle/SlackProperties.kt
slack-plugin/src/main/kotlin/slack/gradle/SlackRootPlugin.kt
slack-plugin/src/main/kotlin/slack/gradle/SlackVersions.kt
slack-plugin/src/main/kotlin/slack/gradle/StandardProjectConfigurations.kt
slack-plugin/src/main/kotlin/slack/gradle/tasks/KtfmtDownloadTask.kt

This PR cleans up a bunch of places where SGP currently expects properties or version catalog versions to exist but aren't actually required. The goal in this is to make the plugin more resuable so we can use it in projects other than the main android repo. Best reviewed commit-by-commit!
There's likely more spots we want to address, but this at least gets it up and running on our internal lints repo as a starting point 👍

Make SGP more reusable

---

slack-plugin/src/main/kotlin/slack/gradle/SlackBasePlugin.kt
slack-plugin/src/main/kotlin/slack/gradle/SlackRootPlugin.kt

Formatters need to apparently be decalred in _both_ the subproject and root project, they just must also be the same. Also fixes delete task handling as spotless will apply the base lifecycle plugin for us before-hand now

Fix spotless applications

---

slack-plugin/src/main/kotlin/slack/gradle/SlackBasePlugin.kt
slack-plugin/src/main/kotlin/slack/gradle/configureBuildTags.kt

This function is resulting in some crashes in CI and is not that useful. Removing it should increase CI reliability.

Remove gradle enterprise `configureBuildTags.kt#addTestSystemProperties`

---

slack-plugin/src/main/kotlin/slack/gradle/StandardProjectConfigurations.kt

We currently maintain a fork of the default rules that we have to manually update every time, let's just define our changes from the defaults instead.

Build upon defaults for detekt

---

slack-plugin/src/main/kotlin/slack/stats/LocTask.kt

We want to always run this because not every module has source files. In those cases we want to just write an empty JSON object for tasks that depend on this task's outputs. This fixes an issue we would see in resources-only projects

Don't skip on empty sources in LocTask

---

gradle/libs.versions.toml
settings.gradle.kts
slack-plugin/build.gradle.kts
slack-plugin/src/main/kotlin/slack/gradle/StandardProjectConfigurations.kt

This completes integration of the napt plugin with some features we requested upstream. This allows us to minimally configure its behavior and get it all building nicely in our main android repo now.

Finish napt integration

---

slack-plugin/src/main/kotlin/slack/stats/LocTask.kt
slack-plugin/src/main/kotlin/slack/stats/ModuleStats.kt

Apparently having an empty input dir just breaks gradle so we need to keep skipwhenempty and instead just handle it as an optional input elsewhere

Make LocData optional instead

---

slack-plugin/src/main/kotlin/slack/gradle/Platforms.kt
slack-plugin/src/main/kotlin/slack/gradle/SlackTools.kt
slack-plugin/src/main/kotlin/slack/gradle/util/JsonTools.kt
slack-plugin/src/main/kotlin/slack/stats/LocTask.kt
slack-plugin/src/main/kotlin/slack/stats/ModuleStats.kt

This is so brittle in Gradle when the file is optional or may not exist. This basically just makes the whole thing work with JSON strings and Super Duper Optional Everywhere.

Don't use files at all for loc data

---

slack-plugin/src/main/kotlin/slack/gradle/SlackBasePlugin.kt
slack-plugin/src/main/kotlin/slack/gradle/SlackExtension.kt
slack-plugin/src/main/kotlin/slack/gradle/SlackGradleUtil.kt
slack-plugin/src/main/kotlin/slack/gradle/SlackProperties.kt
slack-plugin/src/main/kotlin/slack/gradle/StandardProjectConfigurations.kt
slack-plugin/src/main/kotlin/slack/gradle/dependencies/SlackDependencies.kt

This moves compose support to a new DSL configuration instead.
```kotlin
slack {
android {
features {
compose()
}
}
}
```
Currently there is no extra configuration beyond the above in the DSL, but we could add more in the future. This also adds a new `defaultComposeAndroidBundleAlias` property that can be used to identify a default `libs.bundle.*` alias to include in any projects that enable compose. This is, in this case, just focused on adding _core_ compose deps (runtime, ui, etc).
One implementation note is that due to AGP using regular kotlin properties still, we have to make enabling compose a synchronous action that directly sets them on the underlying AGP property under the hood. If they ever convert them into lazy gradle properties, we could look at chaining these instead.

Implement compose() feature DSL in SlackExtension

---

slack-plugin/src/main/kotlin/slack/gradle/SlackVersions.kt
slack-plugin/src/main/kotlin/slack/gradle/StandardProjectConfigurations.kt

This is an annoying new granularity to the compose compiler version checks that we have to handle now.
kotlin 1.7.10, compose expects 1.7.0 => specify
1.7.10 kotlin 1.7.10, compose expects 1.7.10 => omit the arg entirely
https://android-review.googlesource.com/c/platform/frameworks/support/+/2189520

Specify kotlin version in compose compatibility check

---

slack-plugin/src/main/kotlin/slack/gradle/SlackExtension.kt
slack-plugin/src/main/kotlin/slack/gradle/StandardProjectConfigurations.kt

This way we can disable androidTest compilation tasks for variants that don't actually run them

Only enable android test on allowed variants

---

slack-plugin/src/main/kotlin/slack/gradle/SlackExtension.kt
slack-plugin/src/main/kotlin/slack/gradle/StandardProjectConfigurations.kt

We were omitting this before unnecessarily, and it prevents these from reusing shared configuration

Set lint config in android and JVM libraries too

---

slack-plugin/src/main/kotlin/slack/gradle/SlackExtension.kt
slack-plugin/src/main/kotlin/slack/gradle/StandardProjectConfigurations.kt

- Fix using the wrong name for the flavor name check
- Fix not applying this in application projects too

Two quick androidTest allowed variants fixes

---

slack-plugin/src/main/kotlin/slack/gradle/SlackExtension.kt

Necessary on robolectric 4.9+ due to https://github.com/robolectric/robolectric/issues/7456

Add robolectric add-opens args

---

slack-plugin/src/main/kotlin/slack/gradle/StandardProjectConfigurations.kt

We initially set this up to default to treating all variants as disabled if none were defined, when we should be doing the opposite.

Only check allowed androidTest variants if any are defined

---

slack-plugin/src/main/kotlin/slack/gradle/SlackExtension.kt

This forces the project-defined compose compiler version, which is often newer than the actual compose-jb versions.

Automatically add compose compiler dep in multiplatform projects

---

slack-plugin/src/main/kotlin/slack/gradle/StandardProjectConfigurations.kt

This adds basic support for `com.android.test` projects. Nothing too crazy, mostly the `pluginManager` block. The rest are mostly indent changes

Add support for android test projects

---

slack-plugin/src/main/kotlin/slack/gradle/StandardProjectConfigurations.kt

No need to inspect generated code
Moved it to the detekt plugin callback block too so it doesn't configure unnecessarily

Exclude build dirs from detekt

---

slack-plugin/src/main/kotlin/slack/gradle/SlackExtension.kt
slack-plugin/src/main/kotlin/slack/gradle/SlackProperties.kt
slack-plugin/src/main/kotlin/slack/gradle/StandardProjectConfigurations.kt

MergeResources is an expensive task and we currently enable it on every android project by default. However, only Robolectric needs this in our needs, so we can save time by only enabling it when tests need it.
In our internal codebase this brings our CI unit test job down from ~18k tasks to ~15k total tasks. Working on benchmarks with this next to see time improvements.

Only enable androidResources in tests if robolectric is requested

---

agp-handlers/agp-handler-73/src/main/kotlin/slack/gradle/agphandler/v73/AgpHandlerFactory73.kt
agp-handlers/agp-handler-80/src/main/kotlin/slack/gradle/agphandler/v80/AgpHandlerFactory80.kt
agp-handlers/agp-handler-api/src/main/kotlin/slack/gradle/agp/AgpHandler.kt
slack-plugin/src/main/kotlin/slack/gradle/StandardProjectConfigurations.kt

The returned class went from `JniPackagingOptions` to `JniPackaging`, which is a signature change that breaks at runtime.

Backport new jniLibs access in AGP 8 handling

---

slack-plugin/src/main/kotlin/slack/gradle/SlackBasePlugin.kt
slack-plugin/src/main/kotlin/slack/gradle/StandardProjectConfigurations.kt
slack-plugin/src/main/kotlin/slack/gradle/util/kgpUtil.kt

KGP automatically copies arguments from the "real" kotlincompile task [here](https://github.com/JetBrains/kotlin/blob/0e4e53786c1b0341befe8e71a5e6e0bc0e464370/libraries/tools/kotlin-gradle-plugin/src/common/kotlin/org/jetbrains/kotlin/gradle/internal/kapt/KaptGenerateStubsTask.kt#L111-L113) and can result in duplicates if we add them on our own.

Don't apply KotlinCompile configs automatically to stub gen tasks

---

.github/workflows/ci.yml
agp-handlers/agp-handler-73/src/main/kotlin/slack/gradle/agphandler/v73/AgpHandlerFactory73.kt
agp-handlers/agp-handler-80/build.gradle.kts
agp-handlers/agp-handler-80/src/main/kotlin/slack/gradle/agphandler/v80/AgpHandlerFactory80.kt
agp-handlers/agp-handler-api/src/main/kotlin/slack/gradle/agp/AgpHandler.kt
slack-plugin/src/main/kotlin/slack/gradle/StandardProjectConfigurations.kt

packagingOptions now returns `Packaging` instead of `PackagingOptions`, so this further generifies the `AgpHandler` implementation

Update to AGP 8.0-alpha10 and further backport packagingOptions changes

---

README.md
gradle/libs.versions.toml
slack-plugin/src/main/kotlin/slack/gradle/SlackBasePlugin.kt
slack-plugin/src/main/kotlin/slack/gradle/SlackProperties.kt
slack-plugin/src/main/kotlin/slack/gradle/util/PropertyUtil.kt

In GE 3.12+, it has moved the test retry implementation internally and should be used if GE is enabled on the project. This adds support for that + finer grained properties to configure the behavior and its values

Support the gradle enterprise plugin retry implementation

---

slack-plugin/src/main/kotlin/slack/gradle/tasks/BootstrapTask.kt

Resolves #179
Currently in bootstrap we divvy up available memory between two daemons: the kotlin daemon (used for compilation) and gradle daemon (used for literally everything else. Tests, java compilations, dexing, R8, lint, detekt, etc).
Historically, we’ve optimized for the kotlin compilation case locally by allocating 75% of the available memory to the kotlin daemon and 25% to the gradle daemon because that’s what most people were doing locally. However, I’ve lately seen this result in more OOMs during other common things like studio sync and dexing/R8.
Given that we did this previously to optimize things on more thermally constrained devices and now we have M1 macs, we're going to be an even 50/50 split. This would match what we do on CI for gradle daemon-intensive tasks already …

Change memory default

---

README.md
slack-plugin/src/main/kotlin/slack/gradle/StandardProjectConfigurations.kt
slack-plugin/src/main/kotlin/slack/gradle/dependencies/SlackDependencies.kt

Desugar libs 2.0 has multiple artifacts, so we need to source from the `libs.versions.toml` to allow for customizing this instead.

Source desugar libraries from libs.versions.toml instead

---

settings.gradle.kts
sgp-monkeypatch-agp/build.gradle.kts
sgp-monkeypatch-agp/gradle.properties
sgp-monkeypatch-agp/src/main/kotlin/com/android/build/gradle/internal/tasks/MergeFilesTask.kt
slack-plugin/build.gradle.kts

After some investigation, I believe this task is currently breaking remote caching for lint because it has non-deterministic ordering of file merges, resulting in the merged file's content to be different. This introduces a monkey patch of the task (that is - we'll put it on the classpath first so that AGP uses our implementation) that has a system property guard to enable sorting of these files first. This allows us to test this theory out. I've also created a standalone monkeypatch artifact as a toe hold for any future ones we want to add too.
Note the task is copied identically from AGP sources with the exception of the extra block for filtering files.

Introduce monkey patch for MergeFileTask

---

build.gradle.kts
gradle/libs.versions.toml
slack-plugin/src/main/kotlin/slack/gradle/SlackProperties.kt
slack-plugin/src/main/kotlin/slack/gradle/SlackRootPlugin.kt
slack-plugin/src/main/kotlin/slack/gradle/SlackVersions.kt
slack-plugin/src/main/kotlin/slack/gradle/StandardProjectConfigurations.kt
slack-plugin/src/main/kotlin/slack/gradle/tasks/SortDependenciesDownloadTask.kt

This adds a new formatter in the same vein as ktfmt, gjf, etc for sorting dependencies in build files. This is mostly is just about adding the binary download task + automatically enabling the gradle plugin.
https://github.com/square/gradle-dependencies-sorter

Integrate sort-dependencies

---

agp-handlers/agp-handler-80/src/main/kotlin/slack/gradle/agphandler/v80/AgpHandlerFactory80.kt
gradle/libs.versions.toml
slack-plugin/build.gradle.kts
slack-plugin/src/main/kotlin/slack/gradle/SlackExtension.kt
slack-plugin/src/main/kotlin/slack/gradle/SlackVersions.kt
slack-plugin/src/main/kotlin/slack/gradle/StandardProjectConfigurations.kt

- Disable the compose/kotlin version check
- Move the compiler version to alway run when the compose plugin is applied
- Promote the `compose()` DSL to top-level and add a multiplatform option
```kotlin
slack {
features {
compose(multiplatform = true|false)
}
}
```

Improve compose multiplatform support

---

gradle/libs.versions.toml
slack-plugin/build.gradle.kts
slack-plugin/src/main/kotlin/slack/gradle/SlackTools.kt
slack-plugin/src/main/kotlin/slack/gradle/tasks/BaseDownloadTask.kt
slack-plugin/src/main/kotlin/slack/gradle/tasks/DetektDownloadTask.kt
slack-plugin/src/main/kotlin/slack/gradle/tasks/GjfDownloadTask.kt
slack-plugin/src/main/kotlin/slack/gradle/tasks/KtLintDownloadTask.kt
slack-plugin/src/main/kotlin/slack/gradle/tasks/KtfmtDownloadTask.kt
slack-plugin/src/main/kotlin/slack/gradle/tasks/ProgressResponseBody.kt
slack-plugin/src/main/kotlin/slack/gradle/tasks/SortDependenciesDownloadTask.kt
slack-plugin/src/main/kotlin/slack/gradle/tasks/robolectric/DependencyJar.kt
slack-plugin/src/main/kotlin/slack/gradle/tasks/robolectric/UpdateRobolectricJarsTask.kt
slack-plugin/src/main/kotlin/slack/gradle/util/OkHttpExt.kt

Using Gradle's ProgressLogger API ([which is annoyingly internal, but super useful](https://github.com/gradle/gradle/issues/3654)) to get a much nicer progress output.
This also moves robolectric jar downloads to use the worker API, allowing them to parallelize their downloads. On my gigabit wifi, this takes the task runtime down from ~21sec to ~13sec.
This also ultimately removes the custom progressbar lib we used since it's no longer used.
This should almost be two different PRs, but they have overlapping changes in progress listener changes so I decided to keep them together since they're both small.
Gradle may someday change the ProgressLogger API since it's internal, but if that happens we can easily remove it.
**Demo**
https://user-images.githubusercontent.com/1361086/218298297-4280a …

Rework download progress and use workers in robolectric jar downloads

---

sgp-monkeypatch-agp/src/main/kotlin/com/android/build/gradle/internal/tasks/MergeFilesTask.kt

I have no idea why but this was somehow removed in ecb87b6bf334710088ccb1f4eb4220656e88e298

Add back MergeFileTask

---

slack-plugin/src/main/kotlin/slack/gradle/tasks/robolectric/UpdateRobolectricJarsTask.kt

Accidentally left this set to lifecycle instead of debug

Fix noisy robolectric log

---

slack-plugin/src/main/kotlin/slack/gradle/SlackGradleUtil.kt

This was an accidental behavior change introduced in #258

Fix accidental configureEach in namedLazy

---

slack-plugin/src/main/kotlin/slack/gradle/SlackProperties.kt
slack-plugin/src/main/kotlin/slack/gradle/StandardProjectConfigurations.kt

This changes SGP to better support lints in multiple projects by not assuming `checkDependencies` and making baseline file names configurable. Also opportunistically fixes an implicit sam check that wasn't getting enabled before

Better support fully modularized lints

---

slack-plugin/src/main/kotlin/slack/gradle/SlackProperties.kt
slack-plugin/src/main/kotlin/slack/gradle/StandardProjectConfigurations.kt

This allows projects to specify extra rule IDs that should be promoted to error severity at a global level. Otherwise they'd have to have some sort of subprojects config to set this in lint each time.

Add lintErrorRuleIds property

---

slack-plugin/src/main/kotlin/slack/gradle/SlackProperties.kt
slack-plugin/src/main/kotlin/slack/gradle/SlackRootPlugin.kt
slack-plugin/src/main/kotlin/slack/gradle/StandardProjectConfigurations.kt
slack-plugin/src/main/kotlin/slack/gradle/lint/LintTasks.kt

This is similar in structure to #280 but for lints. It creates new `ciLint` and a root `globalCiLint` tasks in the project to ease running things on CI.
This also extracts a lot of lint logic from the bloated `StandardProjectConfigurations` file to this standalone bit of code.
One notable change is that now we run lint for all variants in a project unless otherwise specified. This seems like the right thing to do as we should also be running lint on internal/debug/etc sources too.

Consolidate common lint logic to LintTasks

---

slack-plugin/src/main/kotlin/slack/gradle/SlackProperties.kt
slack-plugin/src/main/kotlin/slack/unittest/UnitTests.kt

This adds a new `enableKover` property to allow for enabling kotlinx-kover anywhere we apply ciUnitTest. It does not currently do any other configuration as we're still testing this out internally.

Add kover property

---

slack-plugin/src/main/kotlin/slack/unittest/UnitTests.kt

Removed JVM arg `UseContainerSupport` from UnitTests as it is not supported for all,
ref: https://www.royvanrijn.com/blog/2018/05/java-and-docker-memory-limits/

Removed unsupported arg from UnitTests

---

gradle/libs.versions.toml
settings.gradle.kts
slack-plugin/build.gradle.kts
slack-plugin/src/main/kotlin/slack/gradle/SlackProperties.kt
slack-plugin/src/main/kotlin/slack/gradle/SlackRootPlugin.kt
slack-plugin/src/main/kotlin/slack/gradle/avoidance/AffectedProjectsComputer.kt
slack-plugin/src/main/kotlin/slack/gradle/avoidance/AffectedProjectsResult.kt
slack-plugin/src/main/kotlin/slack/gradle/avoidance/ComputeAffectedProjects.kt
slack-plugin/src/main/kotlin/slack/gradle/avoidance/ComputeAffectedProjectsTask.kt
slack-plugin/src/main/kotlin/slack/gradle/avoidance/DiagnosticWriter.kt
slack-plugin/src/main/kotlin/slack/gradle/avoidance/GlobUtil.kt
slack-plugin/src/main/kotlin/slack/gradle/util/SgpLogger.kt
slack-plugin/src/test/kotlin/slack/gradle/avoidance/AffectedProjectsComputerTest.kt

This implements a new `ComputeAffectedProjects` task. Most of the relevant docs are on the class and its properties/function itself, but the overview is this task is that it's used to compute affected projects from a given input of changed files (i.e. from a pull request).
**Logic Flow**
1. Parse input changed files
2. Filter input files against a set of input glob patterns to include only relevant files (i.e. source files like `.kt` files)
- If no files patch, no projects are affected!
3. Check filtered files against a set of "never-skippable" glob patterns, such as version catalog files or root build files. If any file matches, the whole change is deemed not skippable and no file is emitted. This, in practice, means "all projects are affected".
4. Map filtered changed files to changed …

Implement ComputeAffectedProjects

---

slack-plugin/src/main/kotlin/slack/gradle/avoidance/AffectedProjectsComputer.kt
slack-plugin/src/main/kotlin/slack/gradle/avoidance/AffectedProjectsDefaults.kt
slack-plugin/src/main/kotlin/slack/gradle/avoidance/ComputeAffectedProjectsTask.kt
slack-plugin/src/test/kotlin/slack/gradle/avoidance/AffectedProjectsComputerTest.kt

1. Make the default patterns public. This allows consumers to more easily reuse them when customizing their own.
2. Use sets for the type to better enforce uniqueness requirements.
3. Add github actions to never-skip defaults.
4. Add excludePatterns to allow finer-grained control. This runs _after_ include filtering so that users can manually exclude certain files that may otherwise be captured in an inclusion filter and is difficult to describe in a simple glob pattern. GitHub action does similar controls for CI matrices.

[Skippy] Improve pattern configuration

---

gradle/libs.versions.toml
slack-plugin/build.gradle.kts
slack-plugin/src/main/kotlin/slack/gradle/Platforms.kt
slack-plugin/src/main/kotlin/slack/gradle/util/JsonTools.kt
slack-plugin/src/main/kotlin/slack/stats/LanguageStats.kt
slack-plugin/src/main/kotlin/slack/stats/LocTask.kt
slack-plugin/src/main/kotlin/slack/stats/ModuleStats.kt

Code gen'd adapters are faster and we'll get better compile-time error checking for mis-configured adapters

Remove moshi-kotlin and only use code gen

---

slack-plugin/src/main/kotlin/slack/gradle/tasks/BootstrapTask.kt

heap dumps by default take up people's space and aren't really actionable, we can debug these ad-hoc when they happen

Use ExitOnOutOfMemoryError for OOMs

---

slack-plugin/src/main/kotlin/slack/unittest/UnitTests.kt

- Write a crash log on failure via CrashOnOutOfMemoryError
- Don't try to cat the log and hprof files
- Write crash log to same location

Improve unit test OOM handling

---

skate-plugin/src/main/kotlin/com/slack/sgp/intellij/SkateService.kt

This shows a CHANGELOG.md file from the root directory and displays it into the "What's New" Panel of the skate plugin. 
Also made it nullable safe.

Allow CHANGELOG.md file to be read into skate plugin

---

slack-plugin/src/main/kotlin/slack/gradle/SlackProperties.kt
slack-plugin/src/main/kotlin/slack/gradle/SlackRootPlugin.kt
slack-plugin/src/main/kotlin/slack/gradle/StandardProjectConfigurations.kt

This is no longer necessary with the new kotlin IC. Includes a couple other cleanups opportunistically

Remove strict kt file checking

---

slack-plugin/src/main/kotlin/slack/gradle/GlobalConfig.kt
slack-plugin/src/main/kotlin/slack/gradle/tasks/robolectric/Sdk.kt
slack-plugin/src/main/kotlin/slack/gradle/tasks/robolectric/UpdateRobolectricJarsTask.kt

Few benefits
- It uses the same dependency resolution settings we have (i.e. artifactory repositories work out of the box)
- Lets gradle to the heavy lifting with both downloading and caching downloads
- Simpler setup for us with task up-to-date ness. Now we just always run the task but the most it every does is copy files. Extremely fast.
Resolves #423, resolves #422, resolves #424

Switch to using detached configurations for robolectric jar downloads

---

.github/workflows/code-review.yml

Over the last day, I’ve made a few changes to how we’re prompting and including context to the github action.
Also I removed the “post errors by default” - so errors will not show up as comments.
In this workflow we also filter out `slack-oss-bot` similar to how we do in `kaldb` (I think this will filter correctly). Example comment: https://github.com/slackhq/kaldb/pull/588#issuecomment-1612152887
This addresses some of your comments from the earlier prototype!

Bump code-review workflow

---

.github/workflows/code-review.yml

Modify workflow to once per PR, remove thumbs up, and find common ancestor for the diff (https://github.com/fxchen/code-review/pull/33/files)

Only comment once per PR and use common ancestor for git diff

---

slack-plugin/src/main/kotlin/slack/dependencyrake/DependencyRake.kt
slack-plugin/src/main/kotlin/slack/gradle/SlackGradleUtil.kt
slack-plugin/src/main/kotlin/slack/gradle/StandardProjectConfigurations.kt

Make dependency rake account for all version catalogs

---

slack-plugin/src/main/kotlin/slack/gradle/SlackProperties.kt
slack-plugin/src/main/kotlin/slack/gradle/lint/LintTasks.kt

Apparently this is not enabled by default 🤦‍♂️

Enable lint on test sources by default

---

docs/dependency-rake.md
slack-plugin/src/main/kotlin/slack/dependencyrake/DependencyRake.kt
slack-plugin/src/main/kotlin/slack/gradle/SlackRootPlugin.kt
slack-plugin/src/main/kotlin/slack/gradle/StandardProjectConfigurations.kt

Misc dependency rake improvements

---

slack-plugin/src/main/kotlin/slack/gradle/StandardProjectConfigurations.kt

Part of Dagger 2.47 and prep for KSP support: https://dagger.dev/dev-guide/compiler-options#ignore-provision-key-wildcards

Add new dagger flag to ignore provisioning keys

---

build.gradle.kts
skate-plugin/build.gradle.kts
skate-plugin/src/main/kotlin/com/slack/sgp/intellij/SkateErrorHandler.kt
skate-plugin/version-templates/Version.kt

Restore copyright + wire in build-time values

---

skate-plugin/src/main/kotlin/com/slack/sgp/intellij/SkateService.kt
skate-plugin/src/main/kotlin/com/slack/sgp/intellij/ui/SkateConfigUI.kt
skate-plugin/src/main/kotlin/com/slack/sgp/intellij/ui/WhatsNewPanelFactory.kt
skate-plugin/src/main/resources/META-INF/plugin.xml

Before this change, if there were no new entries a panel would still appear in the IDE:
Now if there is no text, the panel just simply won't show up (the xml file is open to show that a last date entry was stored) and there will be no tool window registered: 
I also realized that in another PR I may have accidentally merged a change with the settings:
So I reverted that to what it was originally (I am still looking into the wrap text so that will be in another PR):

Don't show "What's New" Panel if no Changelog text is present

---

skate-plugin/src/main/kotlin/com/slack/sgp/intellij/ChangelogParser.kt

Account for both italicized and not italicized dates in the "What's New" files.
In the CHANGELOG file, the dates are wrapped in "_" and the WHATSNEW file, the dates are not.

Cosmetic Bug Fix for Markdown File Rendering (with and without italics) 

---

skate-plugin/src/test/kotlin/com/slack/sgp/intellij/ChangelogParserNoItalicsTest.kt

This is related to a previous [PR](https://github.com/slackhq/slack-gradle-plugin/pull/491) that was just merged, about different formatting with italicized / non italicized entry dates. I created test cases in `ChangelogParserNoItalicsTest.kt` that are now passing because of the pushed change. 
Here are the current tests in a different [file](https://github.com/slackhq/slack-gradle-plugin/blob/main/skate-plugin/src/test/kotlin/com/slack/sgp/intellij/ChangeLogParserTest.kt), but the new tests are in this change.
This is to account for the different possible local date formats found in markdown files.
Here is the side by side comparison of the tests, just removing the "_" to see if the parser is able to still work with a different local date format:

Add Tests for Different Changelog Format with Non-Italicized Dates

---

slack-plugin/src/main/kotlin/slack/gradle/ApkVersioningPlugin.kt

We can move away from having separate version code for each build type now that we're publishing app bundle
This change should also help resolve issues with AGP 8.1 upgrade

Use one version code for all apks

---

slack-plugin/src/main/kotlin/slack/gradle/ApkVersioningPlugin.kt

I forgot to update the default version code for local build in #503. Before, devs usually get 30009999. This PR updates the version to be 90009999 to make it consistent with CI build number

Update default local version code

---

slack-plugin/src/main/kotlin/slack/gradle/StandardProjectConfigurations.kt

This avoids a bug in skippy where we'd mistakenly mark an project as affected in android tests even if it wasn't actually enabled

Don't include androidTest information about projects if it's not enabled

---

skate-plugin/artifactory-authenticator/build.gradle.kts
skate-plugin/artifactory-authenticator/gradle.properties
skate-plugin/artifactory-authenticator/src/main/kotlin/com/slack/intellij/artifactory/ArtifactoryPluginRepositoryAuthProvider.kt
skate-plugin/artifactory-authenticator/src/main/kotlin/com/slack/intellij/artifactory/RepoAuthHotfix.kt
skate-plugin/artifactory-authenticator/src/main/resources/META-INF/plugin.xml

Continuing from #500. Also had to remove the okio dependency as it appears to conflict with dependencies coming from the intellij plugin now, so using standard java to do it. Tested this with studio giraffe (the bugged version) and it works now

Fix authenticator plugin

---

skate-plugin/src/main/kotlin/com/slack/sgp/intellij/ui/WhatsNewPanelFactory.kt

Android Studio frustratingly ships with a broken version of the embedded markdown plugin, which prevents use of the modern JCEF API we were using. This adds a fallback implementation for when that's not available and just uses a simpler html panel. Code blocks don't work and it's a little plain, but it's otherwise ok.

Add fallback Html panel support for markdown rendering

---

docs/dsl.md
slack-plugin/src/main/kotlin/slack/gradle/SlackExtension.kt

This streamlines configuration of enabling `androidResources` and enforces use of a resource prefix to avoid conflicts.
May your avatars never be wrongly sized again.

Add resources DSL

---

build.gradle.kts
skate-plugin/src/main/kotlin/com/slack/sgp/intellij/ChangelogParser.kt
skate-plugin/src/main/kotlin/com/slack/sgp/intellij/util/MemoizedSequence.kt
skate-plugin/src/test/kotlin/com/slack/sgp/intellij/ChangeLogParserTest.kt

This PR rewrites changelog parser logic to use a sequence instead
This makes the changelog parser logic a bit more robust and lazy, while also fixing some specific issues around parsing dates (previously it assumed dates were italicized).

Improve Skate changelog parsing logic

---

agp-handlers/agp-handler-80/src/main/kotlin/slack/gradle/agphandler/v80/AgpHandler80.kt
agp-handlers/agp-handler-api/src/main/kotlin/slack/gradle/agp/AgpHandler.kt
agp-handlers/agp-handler-api/src/main/kotlin/slack/gradle/agp/AgpHandlerFactory.kt
slack-plugin/src/main/kotlin/slack/gradle/AgpHandlers.kt

This is a new first-party API we can now use for this rather than string parsing

Migrate to `AndroidPluginVersion` in `AgpHandler` APIs

---

slack-plugin/src/main/kotlin/slack/unittest/UnitTests.kt

We've been using this in the slack android repo for a few months now and it's going fine

Enable robolectric native graphics by default

---

slack-plugin/src/main/kotlin/slack/gradle/StandardProjectConfigurations.kt

Set the kotlin module name to a dashified version of the project path to ensure uniqueness  in created .kotlin_module files. This is particularly important for kotlin-reflect usages and anything else that introspects kotlin metadata

Set kotlin module names

---

slack-plugin/src/main/kotlin/slack/gradle/Configurations.kt

Works around this issue: https://issuetracker.google.com/issues/301426678

Don't apply boms to core library desugaring's interface

---

skate-plugin/build.gradle.kts
skate-plugin/src/main/kotlin/com/slack/sgp/intellij/SkatePluginSettings.kt
skate-plugin/src/main/kotlin/com/slack/sgp/intellij/modeltranslator/GenerateTranslatorBodyAction.kt
skate-plugin/src/main/kotlin/com/slack/sgp/intellij/modeltranslator/TranslatorAnnotator.kt
skate-plugin/src/main/kotlin/com/slack/sgp/intellij/modeltranslator/helper/TranslatorHelper.kt
skate-plugin/src/main/kotlin/com/slack/sgp/intellij/modeltranslator/model/TranslatorBundle.kt
skate-plugin/src/main/kotlin/com/slack/sgp/intellij/util/StringExtensions.kt
skate-plugin/src/main/resources/META-INF/plugin.xml
skate-plugin/src/main/resources/messages/skateBundle.properties
skate-plugin/src/test/kotlin/com/slack/sgp/intellij/modeltranslator/TranslatorAnnotatorTest.kt
skate-plugin/src/test/kotlin/com/slack/sgp/intellij/modeltranslator/TranslatorHelperTest.kt
skate-plugin/src/test/testData/ActionTranslator.kt
skate-plugin/src/test/testData/Call.kt
skate-plugin/src/test/testData/CallExtensions.kt
skate-plugin/src/test/testData/CallObjectTranslator.kt
skate-plugin/src/test/testData/CallObjectsTranslator.kt
skate-plugin/src/test/testData/CallTranslator.kt
skate-plugin/src/test/testData/FullyQualifiedActionTranslator.kt
skate-plugin/src/test/testData/FullyQualifiedCallTranslator.kt
skate-plugin/src/test/testData/ImportAliasCallTranslator.kt
skate-plugin/src/test/testData/NullableCallTranslator.kt
skate-plugin/src/test/testData/SingleLineCallTranslator.kt

This adds model translator generation to Skate Plugin. It's meant to assist in writing translators to convert API models to domain models by generating a first implementation that can be iterated on after, eliminating the need for doing the tedious repetitive steps.
https://github.com/slackhq/slack-gradle-plugin/assets/3355288/b1938e8f-dea7-414d-9fb2-ab9b91fbba6b

Model translator generation

---

slack-plugin/src/main/kotlin/slack/gradle/StandardProjectConfigurations.kt

Move debugprobes exclusion to release builds only

---

slack-plugin/src/main/kotlin/slack/gradle/ApkVersioningPlugin.kt
slack-plugin/src/main/kotlin/slack/gradle/SlackProperties.kt

Previously, we would use interpolations of CI build numbers and user names for version codes and version names of APKs, resulting in remote build cache misses for anything involving manifests and buildconfig. This optimizes the debug build happy path by ensuring all debug builds have the same values for both, while still using the original heuristics for any other build types.
For slack employees, you can see an example build scan comparison of where this issue arises here: https://gradle-enterprise.tinyspeck.com/c/4ywvch5rawiia/vklqqwvf3ei7s/task-inputs?cacheability=cacheable

Make debug builds use consistent version codes/names on CI

---

slack-plugin/src/main/kotlin/slack/gradle/SlackGradleUtil.kt
slack-plugin/src/main/kotlin/slack/gradle/SlackProperties.kt
slack-plugin/src/main/kotlin/slack/gradle/StandardProjectConfigurations.kt
slack-plugin/src/main/kotlin/slack/gradle/lint/LintTasks.kt

This revamps lint handling in the project to add support for KMP projects (resolves #559) and also incorporates some neat/helpful things I learned from the AndroidX repo's [LintConfiguration](https://github.com/androidx/androidx/blob/cb78132cc8288f85e0ff8f4c32ed58a61b05d7d8/buildSrc/private/src/main/kotlin/androidx/build/LintConfiguration.kt).
This also cleans up a couple old things around handling baseline files and a hidden detector we couldn't use anymore.
Tested this with the CatchUp project: https://github.com/ZacSweers/CatchUp/pull/1032

Revamp lint handling to support KMP + incorporate some ideas from AndroidX

---

skate-plugin/README.md
skate-plugin/build.gradle.kts
skate-plugin/src/main/kotlin/com/slack/sgp/intellij/SkatePluginSettings.kt
skate-plugin/src/main/kotlin/com/slack/sgp/intellij/SkateService.kt
skate-plugin/src/main/kotlin/com/slack/sgp/intellij/WhatsNewToolWindowListener.kt
skate-plugin/src/main/kotlin/com/slack/sgp/intellij/featureflags/FeatureFlagAnnotator.kt
skate-plugin/src/main/kotlin/com/slack/sgp/intellij/projectgen/ProjectGenMenuAction.kt
skate-plugin/src/main/kotlin/com/slack/sgp/intellij/tracing/SkateMetricCollector.kt
skate-plugin/src/main/kotlin/com/slack/sgp/intellij/tracing/SkateSpanBuilder.kt
skate-plugin/src/main/kotlin/com/slack/sgp/intellij/tracing/SkateTraceReporter.kt
skate-plugin/src/main/kotlin/com/slack/sgp/intellij/ui/SkateConfigUI.kt
skate-plugin/src/main/kotlin/com/slack/sgp/intellij/util/ProjectUtils.kt
skate-plugin/src/main/resources/META-INF/plugin.xml
skate-plugin/src/main/resources/messages/skateBundle.properties
skate-plugin/src/test/kotlin/com/slack/sgp/intellij/ProjectGenMenuActionTest.kt
skate-plugin/src/test/kotlin/com/slack/sgp/intellij/SkateTraceReporterTest.kt
skate-plugin/src/test/kotlin/com/slack/sgp/intellij/WhatsNewToolWindowListenerTest.kt
tracing/src/main/kotlin/com/slack/sgp/tracing/model/Spans.kt
tracing/src/main/kotlin/com/slack/sgp/tracing/model/TagBuilder.kt

Add the first set of metrics to be tracked for Skate plugin, including
* Whats New Panel:
* When the What's new panel opened / closed
* Feature Flag Annotator:
* When user clicked on Houston link from feature flag annotation
* Project Generator:
* When the terminal opened and execute command to spin up ProjectGen UI
Noted that for the WhatsNewPanel, I added a custom `WhatsNewToolWindowListener` to subscribe to the event for the window opened/closed. I followed the set up described [here](https://plugins.jetbrains.com/docs/intellij/plugin-listeners.html#defining-project-level-listeners) to set up the listener
Testing:
Example traces sent:
https://analytics.tinyspeck.com/v3/explore/1000000001135498

Add tracing to Skate plugin

---

slack-plugin/src/main/kotlin/slack/gradle/tasks/robolectric/UpdateRobolectricJarsTask.kt

Robolectric 4.11 added support for API 34

Update robolectric jars for API 34

---

agp-handlers/agp-handler-83/build.gradle.kts
agp-handlers/agp-handler-83/src/main/kotlin/slack/gradle/agphandler/v83/AgpHandler83.kt

This has a new API for the current AGP version, allowing us to move off the private API

Update AgpHandler 8.3 to alpha 13

---

slack-plugin/src/main/kotlin/slack/gradle/util/kgpUtil.kt

Similar to stub gen, we don't actually want to configure these even though they extend kotlincompile because KSP applies their own mappings

Don't configure KspTask in KotlinCompile tasks

---

build.gradle.kts

Now they're clickable directly from the dokka docs (see the "source" link in the screenshot)

Includes source links in dokka docs

---

skate-plugin/src/main/kotlin/com/slack/sgp/intellij/SkatePluginSettings.kt
skate-plugin/src/main/kotlin/com/slack/sgp/intellij/codeowners/CodeOwnerFileFetcher.kt
skate-plugin/src/main/kotlin/com/slack/sgp/intellij/codeowners/CodeOwnerInfo.kt
skate-plugin/src/main/kotlin/com/slack/sgp/intellij/codeowners/CodeOwnerRepository.kt
skate-plugin/src/main/kotlin/com/slack/sgp/intellij/ui/CodeOwnerWidget.kt
skate-plugin/src/main/kotlin/com/slack/sgp/intellij/ui/CodeOwnerWidgetFactory.kt
skate-plugin/src/main/kotlin/com/slack/sgp/intellij/ui/SkateConfigUI.kt
skate-plugin/src/main/resources/META-INF/plugin.xml
skate-plugin/src/main/resources/messages/skateBundle.properties
skate-plugin/src/test/kotlin/com/slack/sgp/intellij/codeowners/CodeOwnerRepositoryTest.kt
skate-plugin/src/test/resources/test-code-ownership.csv

This PR adds a code owner widget to the bottom right status bar of Jetbrains IDEs.

Add code owner pane to Skate plugin

---

slack-plugin/src/main/kotlin/slack/gradle/SlackExtension.kt
slack-plugin/src/main/kotlin/slack/gradle/compose/ComposeUtil.kt

This makes it easier to specify custom options to compose in a project.

Expose compilerOptions for compose configuration

---

skate-plugin/src/main/kotlin/com/slack/sgp/intellij/ui/CodeOwnerWidget.kt

Fixes a NPE when `myStatusBar` is null (assuming not yet available or disabled) in codeowners widget update code.

Fix NPE in codeowners widget

---

build.gradle.kts

This is enabled by the progressive flag anyway and ~seemingly~ enabled by default in K2.
Ref: https://youtrack.jetbrains.com/issue/KT-22723/Inconsistent-behavior-of-floating-point-number-comparisons#focus=Change-27-2959679.0-0

Remove `-Xproper-ieee754-comparisons`

---

skate-plugin/src/main/kotlin/com/slack/sgp/intellij/projectgen/ProjectGenMenuAction.kt
skate-plugin/src/main/kotlin/com/slack/sgp/intellij/projectgen/ProjectGenPresenter.kt
skate-plugin/src/main/kotlin/com/slack/sgp/intellij/projectgen/ProjectGenScreen.kt
skate-plugin/src/main/kotlin/com/slack/sgp/intellij/projectgen/ProjectGenUi.kt
skate-plugin/src/main/kotlin/com/slack/sgp/intellij/projectgen/ProjectGenWindow.kt

When project got generated successfully, add an option to `Quit & Sync` that exits project gen dialog and does Gradle sync.
https://github.com/slackhq/slack-gradle-plugin/assets/12748234/469c74b5-baa0-4133-be51-e4820a276b06

Add sync action on successful project gen

---

slack-plugin/src/main/kotlin/slack/gradle/SlackExtension.kt
slack-plugin/src/main/kotlin/slack/gradle/SlackProperties.kt
slack-plugin/src/main/kotlin/slack/gradle/anvil/AnvilMode.kt

This adds a new `AnvilMode` enum + property so we can better test anvil under different scenarios (K1/K2 and kapt/ksp)

Broaden anvil KSP support controls

---

agp-handlers/agp-handler-82/build.gradle.kts
agp-handlers/agp-handler-82/lint-baseline.xml
agp-handlers/agp-handler-83/build.gradle.kts
agp-handlers/agp-handler-83/lint-baseline.xml
agp-handlers/agp-handler-api/build.gradle.kts
agp-handlers/agp-handler-api/src/main/kotlin/slack/gradle/agp/VersionNumber.kt
build.gradle.kts
config/lint/lint.xml
gradle.properties
gradle/libs.versions.toml
sgp-common/build.gradle.kts
skate-plugin/build.gradle.kts
skate-plugin/src/main/kotlin/com/slack/sgp/intellij/projectgen/ProjectGenWindow.kt
skippy/build.gradle.kts
slack-plugin/build.gradle.kts
slack-plugin/lint-baseline.xml
slack-plugin/src/main/kotlin/slack/gradle/tasks/ProgressResponseBody.kt
slack-plugin/src/main/kotlin/slack/gradle/util/ThermalsWatcher.kt
slack-plugin/src/test/kotlin/slack/gradle/util/ThermlogParserTest.kt
tracing/build.gradle.kts
tracing/lint-baseline.xml

This starts running lint checks on the project, including our common compose and slack lints along with a set of gradle lints that google started publishing recently.

Incorporate lint into the project

---

skate-plugin/src/main/kotlin/com/slack/sgp/intellij/projectgen/ProjectGenPresenter.kt
skate-plugin/src/main/kotlin/com/slack/sgp/intellij/projectgen/models.kt

Add `circuit` option to project gen. Once selected, project gen will add circuit set up to new module BUILD file:
```
features {
circuit()
}
```
Screenshot:

Add circuit to project gen option

---

docs/index.md

From main page: note the dashes, some of those are bullet points, some are descriptions of bullet points.
mkdocs's markdown doesn't like non-separate bullet lists.
Most of the project has new lines before lists, except these on the main page.
Example:

Fix mkdocs lists on the main page

---

build.gradle.kts
skate-plugin/README.md

Enable the code to set up change notes. Upon this change, planning to update the Github Action publish job to takes on a Release notes argument and write it to a `change-notes.md` file before running the publish task

Set change notes when publishing Skate

---

skate-plugin/src/main/kotlin/com/slack/sgp/intellij/codeowners/CodeOwnerFileFetcher.kt
skate-plugin/src/test/kotlin/com/slack/sgp/intellij/codeowners/CodeOwnerFileFetcherImplTest.kt

This PR fixes an issue when the code owner file setting is null or missing. Also added a test for this case.

Fix codeowners file fetching issue

---

slack-plugin/src/main/kotlin/slack/gradle/SlackProperties.kt
slack-plugin/src/main/kotlin/slack/gradle/SlackVersions.kt
slack-plugin/src/main/kotlin/slack/gradle/lint/LintTasks.kt

This allows us to specify it programmatically and source our version catalogs rather than only statically in `gradle.properties`

Add property to override lint version

---

build.gradle.kts
skate-plugin/README.md
skate-plugin/change-notes.html
skate-plugin/change-notes.md

Fixed issue with release notes by switching it to HTML from Markdown
Before:

Fix Skate release notes format

---

slack-plugin/src/main/kotlin/slack/gradle/StandardProjectConfigurations.kt

We can't have a provider that captures the enclosing project, so let's just set it directly.

Fix configuration cache when setting module name

---

skate-plugin/src/main/kotlin/com/slack/sgp/intellij/codeowners/CodeOwnerRepository.kt
skate-plugin/src/test/kotlin/com/slack/sgp/intellij/codeowners/CodeOwnerRepositoryTest.kt
skate-plugin/src/test/resources/test-code-ownership.yaml

Adding new properties to our code owners file format shouldn't break marshalling - this PR disables YAML strict mode.

Disable YAML strict-mode marshalling for codeowner widget

---

slack-plugin/src/main/kotlin/slack/gradle/SlackBasePlugin.kt
slack-plugin/src/main/kotlin/slack/gradle/SlackProperties.kt

We were tipped off by our friends at another company that this helps with IDE performance immensely by completely preventing the IDE from indexing build dirs (which tend to be littered with tons of intermediate files, even if untracked). We want to experiment with this flag and see if it improves things for us too.
We might have some plugins that still hardcode lookups to `build` dirs, but we can iterate from here.

Add new flag + logic to relocate project build directories

---

gradle/libs.versions.toml
settings.gradle.kts
skate-plugin/compose-playground/build.gradle.kts
skate-plugin/compose-playground/src/jvmMain/kotlin/slack/tooling/compose/playground/MarkdownPlayground.kt
skate-plugin/compose-playground/src/jvmMain/kotlin/slack/tooling/compose/playground/ProjectGenPlayground.kt
skate-plugin/project-gen/build.gradle.kts
skate-plugin/project-gen/src/jvmMain/kotlin/slack/tooling/markdown/ui/MarkdownPanel.kt
skate-plugin/project-gen/src/jvmMain/kotlin/slack/tooling/projectgen/ProjectGenUi.kt
skate-plugin/src/main/kotlin/com/slack/sgp/intellij/SkateService.kt
skate-plugin/src/main/kotlin/com/slack/sgp/intellij/ui/WhatsNewPanelFactory.kt

This uses a multiplatform compose markdown renderer for markdown rendering, offering a nicer UI for the whatsnew panel since Studio doesn't seem likely to ever support JCEF.
In the process of this, I also made a playground project where we can test compose UIs like this and project gen without needing to run a whole IDE flow to test, to make it easier to iterate. Now it's as easy as just running the `main` functions in those files.
There are still some features missing from the markdown library like strikethrough, dividers, tables, etc, but the maintainer is responsive and I've been filing issues. This builds a best-effort bridge theme based off of Jewel. In the future we may also consider their in-development impl.
| Light | Dark |
| ----- | ---- |
| <img width="820" alt="Screenshot …

Switch to Compose-based markdown rendering solution

---

slack-plugin/src/main/kotlin/slack/unittest/UnitTests.kt

Another migration from gradle enterprise

Switch to develocity.retry API

---

skate-plugin/src/main/kotlin/com/slack/sgp/intellij/codeowners/CodeOwnerRepository.kt
skate-plugin/src/main/kotlin/com/slack/sgp/intellij/codeowners/model/CodeOwner.kt
skate-plugin/src/main/kotlin/com/slack/sgp/intellij/codeowners/model/Path.kt
skate-plugin/src/main/kotlin/com/slack/sgp/intellij/codeowners/model/PathObjectSerializer.kt
skate-plugin/src/main/kotlin/com/slack/sgp/intellij/codeowners/model/StringOrObjectSerializer.kt
skate-plugin/src/test/kotlin/com/slack/sgp/intellij/codeowners/CodeOwnerRepositoryTest.kt
skate-plugin/src/test/resources/test-code-ownership.yaml

The `path` objects for the config are changing, this PR introduces support for the new format.
Currently `paths` looks as follows:
```
paths:
- app/folder1/.*
- app/folder2/.*
- app/folder3/subfolder/.*
```
We are adding a new `notify` flag which means that a `path` can be either a string (i.e. previous format) or an object (new format:
```
paths:
- path: app/folder1/.*
notify: false
- app/folder2/.*
- app/folder3/subfolder/.*
```
This PR introduces a custom deserializer and a Path object to be able to handle the above. The changes are backwards compatible so old configs will still work as usual.
Testing:
- The relevant tests were updated to cover the new config
- I was able to confirm with a local build of SKATE that the new format (and the old format) are working okay

Update codeowners to support new config format

---

slack-plugin/src/main/kotlin/slack/unittest/UnitTests.kt

####
Description:
- I am working on updating our _kover_ version to `0.8.1` in the `slack-android-ng` repo and this workaround is no longer needed and actually fails the command if it's present.
- So removing this and will include this in a future release once the PR is merged to switch over in `slack-android-ng`
- The original issue is now fixed and merged: https://github.com/Kotlin/kotlinx-kover/issues/362

Remove Kover Workaround for `0.7.1`

---

slack-plugin/src/main/kotlin/slack/gradle/lint/LintTasks.kt

- Turning off the `XML` report generation for the Lint task since we don't currently use the XML reports for anything

Turn off xml report generation for lint task

---

slack-plugin/src/main/kotlin/slack/gradle/SlackProperties.kt
slack-plugin/src/main/kotlin/slack/gradle/kgp/KgpTasks.kt

This allows us to force it to a lower version if needed for K2 testing

Add a kapt language version override

---

gradle/libs.versions.toml
skate-plugin/compose-playground/src/jvmMain/kotlin/slack/tooling/compose/playground/MarkdownPlayground.kt
skate-plugin/compose-playground/src/jvmMain/kotlin/slack/tooling/compose/playground/ProjectGenPlayground.kt
skate-plugin/project-gen/build.gradle.kts
skate-plugin/project-gen/src/jvmMain/kotlin/slack/tooling/markdown/ui/MarkdownPanel.kt
skate-plugin/project-gen/src/jvmMain/kotlin/slack/tooling/projectgen/PrefixTransformation.kt
skate-plugin/project-gen/src/jvmMain/kotlin/slack/tooling/projectgen/ProjectGenPresenter.kt
skate-plugin/project-gen/src/jvmMain/kotlin/slack/tooling/projectgen/ProjectGenUi.kt
skate-plugin/project-gen/src/jvmMain/kotlin/slack/tooling/projectgen/UiElement.kt
skate-plugin/project-gen/src/jvmMain/kotlin/slack/tooling/projectgen/models.kt

The latest stable Android Studio is now based on intellij 2024.1, so we can move up to a newer Jewel version. This also moves Skate to use the latest compose-multiplatform alphas (but still only compiles SGP against the latest stable gradle plugin).

Update jewel to 0.23.0

---

skate-plugin/project-gen/src/jvmMain/kotlin/slack/tooling/aibot/ChatPanel.kt
skate-plugin/project-gen/src/jvmMain/kotlin/slack/tooling/aibot/ChatWindow.kt
skate-plugin/project-gen/src/jvmMain/resources/drawable/send.svg
skate-plugin/src/main/kotlin/com/slack/sgp/intellij/aibot/ChatBotToolWindow.kt
skate-plugin/src/main/resources/META-INF/plugin.xml

This is a continuation of #927, but because of the Jewel update in #937, I ended up running into some hiccups with transitioning the project and migrating to a different version of intellij gradle platform plugin. We reverted it back in #947 and this PR reflects the changes that are compatible with the old Jewel version (which is back on main). 
I have included the functionality for user input, where send button clears text, enter clears text, and shift + enter adds new lines. Users can also add multiple lines. I also added a function where the send button is faded and unselectable until there is text input. In future PRs, I will add the chat conversation as well, and this is just a start.
https://github.com/user-attachments/assets/94971a43-476e-4d67-924c-e012c633bc3c

Skate AI Initial Chat User Text Field and Window

---

skate-plugin/project-gen/src/jvmMain/kotlin/slack/tooling/aibot/ChatColors.kt
skate-plugin/project-gen/src/jvmMain/kotlin/slack/tooling/aibot/ChatWindow.kt

In this PR, I added a Chat bubble that will print back the user input. I also set up a function "call api" that will call the DevXP API in the future, but currently sends back the user input as well. The conversation field is also scrollable (with no scroll bar at the moment). 
I am also worried about how there is not much padding once the text input becomes multiple lines (like in example 2 of the video), and was wondering if I could get advice on how to add it, because adding padding modifiers seems to only change the box and not the inner text, and the height parameter is what creates the initial space in the text field.
https://github.com/user-attachments/assets/50c6bf01-a77a-4b4d-950e-a849ad70ef16
EDIT: here is an update based on feedback. Now, the user's messages are on the right …

Chat Bubble and "Conversation" 

---

CHANGELOG.md
slack-plugin/src/main/kotlin/slack/gradle/Configurations.kt

This way we can force newer versions with platform projects on these too

Add SqlDelight DialectClasspath to known configurations

---

CHANGELOG.md
slack-plugin/src/main/kotlin/slack/gradle/GradleExt.kt
slack-plugin/src/main/kotlin/slack/gradle/SlackProperties.kt
slack-plugin/src/main/kotlin/slack/gradle/kgp/KgpTasks.kt

Never realized we didn't allow this in tests, this refreshes the logic for this area a bit and adds a test control.

Update -Werror behavior in kotlin and disallow in tests by default

---

.gitignore
build.gradle.kts
gradle.properties
gradle/libs.versions.toml
settings.gradle.kts
skate-plugin/artifactory-authenticator/build.gradle.kts
skate-plugin/artifactory-authenticator/gradle.properties
skate-plugin/artifactory-authenticator/src/main/resources/META-INF/plugin.xml
skate-plugin/build.gradle.kts
skate-plugin/gradle.properties
skate-plugin/src/main/kotlin/com/slack/sgp/intellij/SkateErrorHandler.kt
skate-plugin/src/main/resources/META-INF/plugin.xml
skate-plugin/src/test/kotlin/com/slack/sgp/intellij/modeltranslator/TranslatorAnnotatorTest.kt
tracing/build.gradle.kts

Mostly straightforward, but I think something is wrong with our model annotators plugin that prevents it from being loaded in this version now, causing its tests to also fail. I'd like to just ignore this test for now since this has clearly been broken for awhile, and will ask the team that authored it to look into it on their own time.

Update to IJ platform 2.0.1 + target IJ 241

---

CHANGELOG.md
slack-plugin/src/main/kotlin/slack/gradle/SlackExtension.kt
slack-plugin/src/main/kotlin/slack/gradle/SlackProperties.kt

See the docs on the two new properties for why we're doing this

Add workaround for source information in KGP/AGP

---

platforms/gradle/foundry-gradle-plugin/src/main/kotlin/Aliases.kt

This removes the nested old alias extensions in favor of running things just through `foundry {}`. This also fixes some deprecation levels to be warning instead of error, as the latter would fail gradle sync unfortunately

Clean up aliases

---

platforms/gradle/foundry-gradle-plugin/src/main/kotlin/foundry/gradle/kgp/KgpTasks.kt

Otherwise the zip() operator will never compute

Provide default for kapt language version

---

CHANGELOG.md
tools/skippy/src/main/kotlin/foundry/skippy/AffectedProjectsComputer.kt

In this case we "know" it's attached to that project, even if that project no longer exists.

Track deleted build files when computing parent projects in Skippy

---

platforms/intellij/skate/src/main/resources/META-INF/plugin.xml

Just commented out the tool window for now because it's not ready yet. So we can do a new Skate release that's compatible with K2.

Disable AI Chat Window for New Skate Release

---

platforms/gradle/foundry-gradle-plugin/src/main/kotlin/foundry/gradle/FoundryProperties.kt
platforms/intellij/compose/build.gradle.kts
platforms/intellij/compose/playground/src/jvmMain/kotlin/foundry/intellij/compose/playground/ProjectGenPlayground.kt
platforms/intellij/compose/src/jvmMain/kotlin/foundry/intellij/compose/projectgen/ProjectGenPresenter.kt
platforms/intellij/compose/src/jvmMain/kotlin/foundry/intellij/compose/projectgen/ProjectGenUi.kt
platforms/intellij/compose/src/jvmMain/kotlin/foundry/intellij/compose/projectgen/models.kt
platforms/intellij/skate/src/main/kotlin/foundry/intellij/skate/projectgen/ProjectGenWindow.kt
tools/foundry-common/src/main/kotlin/foundry/common/FoundryKeys.kt

- Use `Path` APIs
- Make the package prefix configurable using a shared key
- Introduce more generic package prefix property, make the android namespace just defer to it
- Update a few leftover names

Small project gen updates

---

build.gradle.kts

Source blockmapFile from generator task

---

platforms/intellij/skate/change-notes.html
publish_skate.sh
release.sh
tools/scripts/scriptUtil.sh

Now we get tags and automatic changelog management. This tunes the publish command to now take either a specific version or an automatic version via `--major/--minor/--patch` argument.
`./publish_skate --major` or `./publish_skate 0.8.1`.
We should now start adding to the "Unreleased" section when we make changes, similar to what we do with the top-level CHANGELOG.md for foundry changes.

Improve Skate publishing

---

CHANGELOG.md
platforms/gradle/foundry-gradle-plugin/src/main/kotlin/foundry/gradle/stats/ModuleStats.kt

Otherwise this would fail to execute because the dir doesn't exist

Don't depend on build sources in mod score if `MODULE_SCORE_INCLUDE_GENERATED` is false

---

CHANGELOG.md
gradle/libs.versions.toml
gradle/wrapper/gradle-wrapper.properties
platforms/gradle/foundry-gradle-plugin/build.gradle.kts
platforms/gradle/foundry-gradle-plugin/lint-baseline.xml
platforms/gradle/foundry-gradle-plugin/src/main/kotlin/foundry/gradle/FoundryBasePlugin.kt
platforms/gradle/foundry-gradle-plugin/src/main/kotlin/foundry/gradle/FoundryExtension.kt
platforms/gradle/foundry-gradle-plugin/src/main/kotlin/foundry/gradle/FoundryProperties.kt
platforms/gradle/foundry-gradle-plugin/src/main/kotlin/foundry/gradle/GlobalConfig.kt
platforms/gradle/foundry-gradle-plugin/src/main/kotlin/foundry/gradle/StandardProjectConfigurations.kt
platforms/gradle/foundry-gradle-plugin/src/main/kotlin/foundry/gradle/model/ModuleTopographyTask.kt
platforms/gradle/foundry-gradle-plugin/src/main/kotlin/foundry/gradle/topography/ModuleTopographyTask.kt
platforms/gradle/foundry-gradle-plugin/src/main/kotlin/foundry/gradle/topography/models.kt
platforms/gradle/foundry-gradle-plugin/src/main/kotlin/foundry/gradle/util/JsonTools.kt
platforms/intellij/compose/lint-baseline.xml
platforms/intellij/skate/lint-baseline.xml
tools/cli/lint-baseline.xml
tools/cli/src/main/kotlin/foundry/cli/CliUtil.kt
tools/skippy/lint-baseline.xml

This PR introduces two new tasks to Foundry.
1. `ModuleTopographyTask` (name: `moduleTopography`). This task reads various information about a module's build features and dumps them to a JSON file. At the moment these features hard coded directly in source, but in the future we could look at trying to make this a more configurable JSON format that could be configurable per-repo. The idea is that this offers a way to get insight into what build features a module has in a way that other tools can then read from. For example - mod score could read this rather than its current, non-reusable implementation.
2. `ValidateModuleTopographyTask` (name: `validateModuleTopography`). This is a sister task to the first one, reading its outputs and then just validating that each _declared_ feature is …

Initial pass at ModuleTopographyTask

---

platforms/gradle/foundry-gradle-plugin/src/main/kotlin/foundry/gradle/stats/ModuleStats.kt

See the comments in code for why we're allowing this. Hopefully just a stopgap until we can finally use native test fixtures everywhere.

Paper over test fixture dependency cycles in mod score computation

---

CHANGELOG.md
platforms/gradle/foundry-gradle-plugin/src/main/kotlin/foundry/gradle/lint/DetektTasks.kt

Detekt's exclude() API is quite weird and pattern matches don't work because it only starts from src roots

Improve detekt exclusion of build dir files

---

.github/workflows/ci.yml

- Fix location of roborazzi outputs (was previously just pointing at the the main sources rather than where reports)
- Fix the reports file name to disambiguate from the usual job

Fix snapshot tests job on CI

---

tools/cli/api/cli.api
tools/cli/src/main/kotlin/foundry/cli/buildkite/BuildkiteDataBindings.kt

The JsonObject types are leftover from the API generator we used and overkill for what we need. This aligns them all to just be simple Map<String, String>

Fix buildkite env vars

---

platforms/gradle/foundry-gradle-plugin/src/main/kotlin/foundry/gradle/topography/ModuleTopographyTask.kt
platforms/gradle/foundry-gradle-plugin/src/main/kotlin/foundry/gradle/topography/ValidateModuleTopographyTask.kt

Split out ValidateModuleTopographyTask

---

CHANGELOG.md
platforms/gradle/better-gradle-properties/api/better-gradle-properties.api
platforms/gradle/better-gradle-properties/src/main/kotlin/foundry/gradle/properties/PropertyResolver.kt

This helps avoid subtle bugs with blank providers

Add blank behavior controls to PropertyResolver.optionalStringProvider

---

platforms/gradle/foundry-gradle-plugin/src/main/kotlin/foundry/gradle/StandardProjectConfigurations.kt

This is needed in order to run instrumentation tests locally.

Add orchestrator dep when androidTest is enabled

---

CHANGELOG.md
platforms/gradle/foundry-gradle-plugin/src/main/kotlin/foundry/gradle/AnnotationProcessing.kt
platforms/gradle/foundry-gradle-plugin/src/main/kotlin/foundry/gradle/FoundryProperties.kt

This way these can be controlled repo-side

Gate dagger processing options behind a property instead

---

platforms/gradle/foundry-gradle-plugin/src/main/kotlin/foundry/gradle/AnnotationProcessing.kt
tools/skippy/src/main/kotlin/foundry/skippy/ComputeAffectedProjectsCli.kt

Make --android-test-project-paths optional in Skippy

---

tools/skippy/src/main/kotlin/foundry/skippy/AffectedProjectsComputer.kt
tools/skippy/src/main/kotlin/foundry/skippy/SkippyConfig.kt
tools/skippy/src/test/kotlin/foundry/skippy/SkippyConfigTest.kt

This introduces the ability specify overlay rules when overlaying with the global config. This allows us to specify local configs that explicitly do not merge with global configs

Add skippy overlay controls

---

CHANGELOG.md
platforms/gradle/foundry-gradle-plugin/src/main/kotlin/Aliases.kt
platforms/gradle/foundry-gradle-plugin/src/main/kotlin/foundry/gradle/FoundryGradleUtil.kt
platforms/gradle/foundry-gradle-plugin/src/main/kotlin/foundry/gradle/FoundryVersions.kt
platforms/gradle/foundry-gradle-plugin/src/main/kotlin/foundry/gradle/testing/UnitTests.kt
platforms/gradle/foundry-gradle-plugin/src/main/kotlin/foundry/gradle/util/JavaAgentArgumentProvider.kt
platforms/gradle/foundry-gradle-plugin/src/main/kotlin/foundry/gradle/util/JavaAgentDependenciesExtension.kt

Introduce a new `testJavaAgents` API for simplifying the configuration of Java agents in test environments. The basic entry point is
```kotlin
dependencies {
testJavaAgents {
javaAgent(...)
}
}
```
With a convenience (deprecated) `mockitoAgent()` (which is what spurred this)

Add support for Java agent configuration in tests

---

platforms/intellij/skate/src/main/kotlin/foundry/intellij/skate/gradle/CopyGradleProjectAccessorPathProvider.kt
platforms/intellij/skate/src/main/kotlin/foundry/intellij/skate/gradle/CopyGradleProjectPathProvider.kt
platforms/intellij/skate/src/main/kotlin/foundry/intellij/skate/gradle/GradleProjectUtils.kt
platforms/intellij/skate/src/main/resources/META-INF/plugin.xml
platforms/intellij/skate/src/test/kotlin/foundry/intellij/skate/gradle/GradleProjectUtilsTest.kt

Resolves #1049
Took some inspo from IntelliJ's https://github.com/JetBrains/intellij-community/blob/d964c13ab2050a89bba5b6be5dea15d0352c1268/plugins/git4idea/src/git4idea/actions/CopyRepositoryRootPathProvider.kt#L11

Add gradle path copy actions to Skate

---

platforms/gradle/foundry-gradle-plugin/src/main/kotlin/foundry/gradle/FoundryExtension.kt
platforms/gradle/foundry-gradle-plugin/src/main/kotlin/foundry/gradle/FoundryProperties.kt

includeSourceInformation is always enabled in kotlin 2.1.20
live literals are gone in newer AGP versions

Remove old compose workarounds

---

build.gradle.kts
platforms/intellij/skate/gradle.properties
platforms/intellij/skate/src/main/kotlin/foundry/intellij/skate/ui/SkateConfigUI.kt

I realized we missed updating to intelliJ `2024.3` in the `build.gradle.kts` file.
Also adjusted in `SkateConfigUI` based on this error message:
```
> Task :platforms:intellij:skate:compileKotlin FAILED
e: file:///Users/liu.k/Developer/foundry/platforms/intellij/skate/src/main/kotlin/foundry/intellij/skate/ui/SkateConfigUI.kt:56:9 Using 'textFieldWithBrowseButton(String? = ..., Project? = ..., FileChooserDescriptor = ..., ((chosenFile: VirtualFile) -> String)? = ...): Cell<TextFieldWithBrowseButton>' is an error. Use [Row.textFieldWithBrowseButton(String, Project?, ((VirtualFile) -> String)?)] or [Row.textFieldWithBrowseButton(FileChooserDescriptor, Project?, ((VirtualFile) -> String)?)] together with [FileChooserDescriptor.withTitle]
[Incubating] Problems report is available at: …
```

Upgrade skate and intellij versions and fixes

---

platforms/intellij/skate/src/main/kotlin/foundry/intellij/skate/projectgen/ProjectGenMenuAction.kt
platforms/intellij/skate/src/main/kotlin/foundry/intellij/skate/projectgen/ProjectGenWindow.kt
platforms/intellij/skate/src/test/kotlin/foundry/intellij/skate/projectgen/ProjectGenWindowTest.kt

We've received several notes about project gen deadlocking newer versions of Android Studio, and here is the [issue](https://github.com/slackhq/foundry/issues/1288) for it.
I was able to reproduce the issue on main.
After the changes, I'm able to load the subproject without deadlock:
I wrote a few unit tests to confirm:
- `onOk` is called on `.doOKAction()` and `.dismissDialogAndSync()`.
- the Dialog is explicitly not modal.
- `onOk` is not called when cancelled.

Prevent Project Gen deadlock with invokeLater and a modeless dialog

---

CHANGELOG.md
platforms/gradle/foundry-gradle-plugin/src/main/kotlin/foundry/gradle/testing/UnitTests.kt

Always set target SDK in androidx.benchmark projects

---

platforms/gradle/foundry-gradle-plugin/src/main/kotlin/foundry/gradle/FoundryBasePlugin.kt
platforms/gradle/foundry-gradle-plugin/src/main/kotlin/foundry/gradle/avoidance/ProjectDependenciesDumpTask.kt

This pull request introduces the `ProjectDependenciesDumpTask`, an alternative to `GenerateDependencyGraphTask`, where we'll generate simple direct deps and construct a dag ourselves outside of gradle

Implement ProjectDependenciesDumpTask

---

platforms/gradle/foundry-gradle-plugin/src/main/kotlin/foundry/gradle/StandardProjectConfigurations.kt
platforms/intellij/compose/src/jvmMain/kotlin/foundry/intellij/compose/projectgen/models.kt

We can use just this simple API now to do this and avoid needing to add a dummy manifest just to set this

Simplify debuggable androidTest

---

CHANGELOG.md
platforms/gradle/foundry-gradle-plugin/lint-baseline.xml
platforms/gradle/foundry-gradle-plugin/src/main/kotlin/foundry/gradle/FoundryExtension.kt
platforms/gradle/foundry-gradle-plugin/src/main/kotlin/foundry/gradle/FoundryProperties.kt
platforms/gradle/foundry-gradle-plugin/src/main/kotlin/foundry/gradle/StandardProjectConfigurations.kt
tools/skippy/lint-baseline.xml

In KSP 2.0.2 they've changed this a bit and now we need to just defensively patch this always

Always defensively patch KSP tasks with sqldelight and viewbinding

---

build.gradle.kts
gradle/all-projects.txt
platforms/gradle/agp-handlers/agp-handler-api/build.gradle.kts
platforms/gradle/foundry-gradle-plugin/build.gradle.kts
platforms/intellij/compose/build.gradle.kts
platforms/intellij/compose/playground/build.gradle.kts
platforms/intellij/skate/build.gradle.kts
platforms/intellij/skate/src/main/kotlin/foundry/intellij/skate/SkatePluginSettings.kt
platforms/intellij/skate/src/main/kotlin/foundry/intellij/skate/gradle/GradleProjectAnnotator.kt
platforms/intellij/skate/src/main/kotlin/foundry/intellij/skate/gradle/GradleProjectCompletionContributor.kt
platforms/intellij/skate/src/main/kotlin/foundry/intellij/skate/gradle/GradleProjectReference.kt
platforms/intellij/skate/src/main/kotlin/foundry/intellij/skate/gradle/GradleProjectReferenceProvider.kt
platforms/intellij/skate/src/main/kotlin/foundry/intellij/skate/gradle/GradleProjectUtils.kt
platforms/intellij/skate/src/main/kotlin/foundry/intellij/skate/gradle/ProjectPathService.kt
platforms/intellij/skate/src/main/kotlin/foundry/intellij/skate/gradle/RefreshProjectPathsIntentionAction.kt
platforms/intellij/skate/src/main/kotlin/foundry/intellij/skate/ui/SkateConfigUI.kt
platforms/intellij/skate/src/main/resources/META-INF/plugin.xml
platforms/intellij/skate/src/main/resources/messages/skateBundle.properties
platforms/intellij/skate/src/test/kotlin/foundry/intellij/skate/gradle/GradleProjectAnnotatorIntegrationTest.kt
platforms/intellij/skate/src/test/kotlin/foundry/intellij/skate/gradle/GradleProjectAnnotatorTest.kt
platforms/intellij/skate/src/test/kotlin/foundry/intellij/skate/gradle/GradleProjectCompletionTest.kt
platforms/intellij/skate/src/test/kotlin/foundry/intellij/skate/gradle/GradleProjectReferenceTest.kt
platforms/intellij/skate/src/test/kotlin/foundry/intellij/skate/gradle/ProjectPathServiceIntegrationTest.kt
platforms/intellij/skate/src/test/kotlin/foundry/intellij/skate/gradle/ProjectPathServiceTest.kt
settings.gradle.kts
tools/cli/build.gradle.kts
tools/skippy/build.gradle.kts

This adds IDE support for project dependencies in Skate after moving off of gradle's type-safe project accessors. This sources known projects from `gradle/all-projects.txt`.
This was also a vibe coding exercise with claude code, so keep an eye out for odd AI issues.
**Highlights**
- Error lines if the project referenced isn't recognized
- Autocomplete for known projects
- Reference support (i.e. jump to) for paths to open their build file.
Filed [this issue](https://issuetracker.google.com/issues/429140552) separately to try to reduce noise from the Android plugin.
Some future work could include
- Making this work if sync fails (for some reason it doesn't currently, seemingly because the underlying PSI is deemed unindexed)
- Possibly supporting other sources of included projects …

Add project path dependency completions to Skate

---

tools/skippy/src/main/kotlin/foundry/skippy/AffectedProjectsComputer.kt
tools/skippy/src/main/kotlin/foundry/skippy/AffectedProjectsResult.kt
tools/skippy/src/main/kotlin/foundry/skippy/SkippyOutput.kt
tools/skippy/src/main/kotlin/foundry/skippy/SkippyRunner.kt
tools/skippy/src/test/kotlin/foundry/skippy/AffectedProjectsComputerTest.kt
tools/skippy/src/test/kotlin/foundry/skippy/SkippyRunnerTest.kt

Similar to what we do for Focus, we now output a list of projects which can be piped through to Spotlight.

[Skippy] Add Spotlight output
